### ISSUE TITLE
Klein star full emc on upgrade bug

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1004]
This is with the recent commits merged. Klein stars seem to be upgraded with full emc rather than just the emc that was in the stars. My only guess for this, is it's reading the wrong emc value when adding to the new one, adding the emc of the item, rather than stored.

**Comment by Lilylicious** [comment]
Fixed in PR #1005. The resulting EMC value was not being set to 0 when that was the result, instead it was left as the previously crafted non-zero value. If you craft with four full stars, you get a full result. If you then craft with 4 empty, you still get full. Two full and two empty before four empty would give a half full star.

Just waiting to get it merged.

**Comment by MaPePeR** [comment]
Should be fixed with #1005 being merged

**Comment by pupnewfster** [comment]
Can be closed as #1005 was merged
