### ISSUE TITLE
Alchemical chest dupe bug

### ISSUE THREAD

**Issue by bochen415** [sinkillerj/ProjectE#1031]
One of our Tekkit Legends player [submitted](http://i.imgur.com/W8OljHR.png) a bug report with a dupe bug.
Here's the video: https://youtu.be/KYva0r0FUz8

I have replicated that with:
ProjectE-1.7.10-PE1.9.2
NotEnoughItems-1.7.10-1.0.5.111-universal
CodeChickenCore-1.7.10-1.0.7.47-universal
MinecraftForge 10.13.4.1517-1.7.10
Testing environment (manual crash): http://paste.ubuntu.com/12634920/

Steps:
1. Place a Alchemical Chest
2. Place Red Matter in the chest
3. Place tnt close (enough) to the chest with a lever
4. Place a vanilla dispenser with a lever far enough so the blast doesn't get it. Get back to the tnt.
5. Switch the lever on the tnt **and immediately** open the Alchemical Chest gui, wait for explosion.
6. After the explosion take the Red Matter out of the still open chest gui.
7. Insert the Red Matter in the dispenser and switch the lever on/off more than once.

**Comment by sinkillerj** [comment]
The core issue should be a easy fix as the Alchemical Chest and Condensers are supposed to be blast proof. As for the part with the dispenser that is gonna take quite a bit more research, I have no idea whats going on there.

**Comment by sinkillerj** [comment]
With ead6f4d this should no longer be possible, however I am going to leave the issue open for now so that more research can be conducted on the dispenser issue.

**Comment by williewillus** [comment]
This is because our container classes (or gui, don't remember which) don't check that the block that activated them is still valid like vanilla does (e.g. a workbench container checks every tick that the cords have a workbench and that the player is within 8 blocks Euclidean distance)

Fix would be to just steal those from vanilla and put them into ours.
And presumably this bug applies to all of our blocks that have containers.

**Comment by MaPePeR** [comment]
I think the dispenser part of the dupe is caused by an item stack with a negative stacksize. 
The dispenser decrements the stacksize, but checks for =0 instead of <=0.
Maybe the initial stacksize is 0 and the dispenser decrements it first without checking. 

The item in the dispenser and the item on the ground and in the inventory probably reference the exact same item stack instance.
