### ISSUE TITLE
Pedestal renders incorrectly on Linux

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1078]
This is weird, the pedestal is inverted and couple blocks too high in the 1.7.10 master of my dev env on Linux. Nothing on Windows. OpenJDK 8u65 64 bit and Intel graphics with the normal open source drivers.

Anyone seen this before?

**Comment by sinkillerj** [comment]
No issue on OpenJDK 7, nor official Java 7, worked fine back when I had Nvidia graphics, and still works fine now that I'm stuck on ancient Intel integrated. I generally work with obj, not block model, but your code does seam correct beyond the culling change which is bad practice. My first thought would be to try other mods such as Decocraft and see if the issue is on your end.

**Comment by sinkillerj** [comment]
Actually scratch that, I'm seeing it on OpenJDK 7 now too, which is strange given that the file hasn't changed since I took those preview screenshots.

**Comment by sinkillerj** [comment]
Tested my fix on OpenJDK 7, had @MaPePeR test it on windows, should be good to go, though I am still massively confused.

![](http://orig00.deviantart.net/a802/f/2015/305/1/0/meh_by_mandalorianjedi-d9f43u2.jpg)

**Comment by Carbon-Ghost** [comment]
_. ._ ( blushing )
