### ISSUE TITLE
While flying in Creative with gem armor and having the Rending Gale breaks it when going back to survival

### ISSUE THREAD

**Issue by SteelShot** [sinkillerj/ProjectE#1235]
Pretty much what title says, if you are flying in creative with the Gem armor and you have the Rending Gale and you switch back to survival the rending gale stops working, the armor flies but hover doest not work (double tab spacebar).

This is fixable by unequiping the armor and putting it back on.
Not a major issue, but being a server owner sometimes even more ofter requires going into creative.

NOTE: This happens only after flying in creative, by swithing to it, it does nothing. Push back mobs ability unaffected
ProjectE version would be the last one on curseforge: ProjectE-1.7.10-PE1.9.5

EDIT1: I've just noticed that the armor has hover capabilities? Tho that is also broken when switching back from creative to survival.

**Comment by Starwort** [comment]
I think this happens because going into creative and attempting to fly sets a tag on you, telling the game that you can fly. When you stop flying, the tag gets removed. ProjectE sets the tag upon correct placement of those items, NOT when attempting to fly. therefore, flying in creative removes the tag so you can't fly.
