### ISSUE TITLE
Some things still don't have EMC values

### ISSUE THREAD

**Issue by Partonetrain** [sinkillerj/ProjectE#1267]
metals.json is valid JSON, and it is set to load in the config by default, but I still can't get modded metals to have EMC values without setting them myself with commands. 

![2016-06-15_17 57 48](https://cloud.githubusercontent.com/assets/19861808/16100259/b5aa378a-3322-11e6-8f55-8c004acc0c16.png)

Mushrooms (the small ones, not the big block ones) don't have EMC values either.

Also, should meats like listAllporkcooked have EMC values?

**Comment by MaPePeR** [comment]
Is your ProjectE up to date? 
Do you have a pregenerated emc file?

**Comment by Lightwave413** [comment]
You already reported this in  #1261   They haven't released a new version since fixing it.  And manually changing the metals.json file does nothing, as stated in the file:

  "comment": "Sets default conversions for various metals from other mods",
  "comment_1": "This file is only shown as an example, it will be regenerated every time mapping occurs in order to let us",
  "comment_2": "change default values. To specify your own custom values use a separate JSON or the /projecte commands ingame",

Though yeah, the mushrooms missing an EMC value strikes me as odd.

**Comment by JosEffigy** [comment]
This is really starting to get annoying... we need dynamicEMC or something for ProjectE.
I get so annoyed that "Oak wood planks", "Dark Oak Wood", etc. dont have emc values despite being vanilla and using oredictionary

**Comment by MaPePeR** [comment]
You come of as very rude. Change your tone. 

ProjectE has and always had "dynamicEMC".

Dark oak wood not having a default value is a bug for which the fix is waiting to be released. (you are using early beta software!) 

You can and always could, however, manually add emc values to things by using the commands and configuration files provided by ProjectE. 

You are really starting to get annoying.

**Comment by williewillus** [comment]
ProjectE has had "dynamic EMC" since December 2014

Updates are slow because, I'm sorry, all three of us have jobs and things to tend to. I mod only on some nights and weekends now as opposed to all day all summer.

Not to mention you are using a beta release.

Regarding the issue it will be resolved in the next build

**Comment by JosEffigy** [comment]
I apologize, i don't know what the norm is for github. I may have overstepped my bounds, sorry.

**Comment by williewillus** [comment]
No problem, we've seen worse before

Cheers

**Comment by williewillus** [comment]
fixed in latest
