### ISSUE TITLE
[Suggestion] EMC variable for Vanilla Scoreboards

### ISSUE THREAD

**Issue by Articdive** [sinkillerj/ProjectE#1395]
Would be quite useful for Server Owners who want to keep track of their EMC on a sidebar or for entire teams to keep track of the Total EMC they own,

/scoreboard objectives add "name" *emc* would allow a Minecraft variable to count/search for the EMC in all transmutation tablets added together, 
/scoreboard teams option "teamName"  *ShareEMC* would allow teams to share EMC between their players in a transmutation tablet.
I'm no modder and have no idea if you were to be able to do this, but i beleive for the few roleplay-modded servers this would be extremely useful, then again its probably for the 99% of all other players completely useless.

"" = is changeable in MC itself, just the name of the scoreboard/title
** = customVariable which i hope you add,

**Comment by sinkillerj** [comment]
Sharing EMC is unrealistic given the way we save it right now, but having a EMC scoreboard should be possible assuming that it can read from the player file.

**Comment by williewillus** [comment]
yay new feature! Use the criteria "projecte:emc_score" to access it.

was super simple to add because the emc only changes when you're in the transmutation interface
so score just needs to be updated on login and in the interface - catch it in the next release

as for the sharing, it's possible but not without lots of work, closing this for now in deference to the other issues open about it ( #306 etc )
