### ISSUE TITLE
[1.10.2] - Random Server Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [sinkillerj/ProjectE#1535]
https://pastebin.com/kNMgGHys

**Comment by EPIICTHUNDERCAT** [comment]
Got another random crash from ya, nothing we did triggered it. just kept on crashing the server on a loop, I had to kill the server and start again in order for it to fix itself. /shrug

https://pastebin.com/w47663u8

They seem similar so i put it here

**Comment by MaPePeR** [comment]
Your server hang watchdog kills the server because emc calculation is happening/takes some time. Start it without it once and generate a "pregenerated emc file". Need to redo that for emc value changes.

**Comment by EPIICTHUNDERCAT** [comment]
I'm confused, so I have to Reset the EMC Ive set and generate the pre-generated EMC file? and then redo the emc value changes? is that what youre saying lol

**Comment by williewillus** [comment]
I mean, the calcylation should not take that long even with lots of mods. The algorithm should be efficient enough for hundreds of items

**Comment by MaPePeR** [comment]
Really depends on the size of the pack and I've never seen it go into infinite loop, so I suspect it's just taking longer than the watchdog allows for. (and there are other mods adding to that time as well - PE is only the mod that is killed because it is active when the time runs out) 

What you should do is: increase the watchdog time. If that doesn't help disable it and see what happens. If that fixes it you can turn on the pregenerate option and trigger a emc recalculation and enable the watch dog again. 

Just be aware that if you want to make any emc changes you need to delete the pregenerated emc file and repeat the process above.

**Comment by EPIICTHUNDERCAT** [comment]
The pack is quite large, and wow thats intense :P what exactly is watchdog and how would i extend the time.

**Comment by MaPePeR** [comment]
Watchdog is a mod you have installed... 

It might be called something else, but it is supposed to restart the server automatically if it hangs or crashes.

**Comment by MaPePeR** [comment]
It might be wrong: I just noticed there is a `net.minecraft.server.dedicated.ServerHangWatchdog` in the log, so the watchdog might be a (new?) vanilla "feature"...

**Comment by Tencao** [comment]
Would also like to contribute my log to this case as it happened when I launched the server right after the worlds loaded, second boot was fine. 

https://paste.ee/r/ax67T

**Comment by williewillus** [comment]
server watchdog is a 1.8 ish thing :P

**Comment by MaPePeR** [comment]
Do you know what it does? Can we fix this somehow?

**Comment by williewillus** [comment]
it's just a thread that kills the server if a tick takes too long, the solution is to not have it take so long ;p

**Comment by MaPePeR** [comment]
Apparently it also happens on server start and Tencao said when it didn't crash emc calculation only took 2.5 seconds.

**Comment by williewillus** [comment]
after the mapping efficiency fix made a while back this shouldn't be a problem anymore
