### ISSUE TITLE
1.12.1 Transmutation Tablet Incorrect GUI Orientation

### ISSUE THREAD

**Issue by Geogiepoegie** [sinkillerj/ProjectE#1572]
Within the transmutation tablet, the GUI places the highest EMC value item at 10:00 instead of 12:00 like it should

**Comment by Mocha2007** [comment]
I noticed this a while back. Correct me if I'm wrong but I think this is intentional. The values descend clockwise from 10:00 instead of downward from 12:00. Personally I prefer the older sorting method too.

**Comment by Geogiepoegie** [comment]
It may be intentional, but why would that be the case? What prompted them to say 10:00 was the new #1?

**Comment by pupnewfster** [comment]
For reference, in EE2 this is how it was 
![image](https://user-images.githubusercontent.com/1203288/53837663-23696c80-3f61-11e9-8684-8485692fa13f.png)
Top center was highest and bottom center was lowest, the line goes from highest to lowest in decreasing order. Not sure which is better, just adding an image so that it is more clear to anyone who looks at this in the future, that it isn't talking about rotating the current thing slightly. (Which is what I thought the issue meant at first)

**Comment by Mocha2007** [comment]
I have to admit, I still prefer the old system, and it's so much more intuitive that I _still_ make the mistake of assuming the top item is the highest-EMC item.

**Comment by williewillus** [comment]
old ee2 arrangement is way too convoluted, I'd just go with highest to lowest in a circle. Highest should be at 12:00 though, not 10:00, so this is valid

**Comment by pupnewfster** [comment]
I agree, which is why I thought that is what this was asking about initially, but decided to make a picture of how it was so that we could get some input.

**Comment by pupnewfster** [comment]
@williewillus clockwise or counter clockwise?
