### ISSUE TITLE
Watch of Flowing Time on dm pedestal should not affect energy collectors.

### ISSUE THREAD

**Issue by pnupy** [sinkillerj/ProjectE#1607]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.10.2-PE1.3.1
Exact Forge version:
12.18.3.2488
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Place energy collector (any kind)
2. Place dark matter pedestal
3. Place watch of flowing time on pedestal and activate
4. Observe the absurd speed you can create EMC

What I expected to happen:
The watch of flowing time should not affect energy collectors as it is extremely unbalanced (as unbalanced as this mod already is). It should probably have a blacklist in the config.
What happened instead:
The watch affected the energy collector and caused it to produce EMC at an absurd rate.

**Comment by williewillus** [comment]
works as intended

**Comment by GhostShot3** [comment]
@sinkillerj Honestly, in my opinion and with all due respect, I don’t think this should affect that block from the mod, since it makes everything extremely fast.
Another major issue is that the clock/pedestal can stack. You can place around four active clocks near collectors and make everything extremely fast to rush endgame. The pedestal/clock cost is also quite cheap in the midgame, and even placing just one is already enough to speed up progression and obtain more of them quickly.
There should probably be a small limit to prevent clock stacking, maybe a maximum of one per chunk or within a certain radius. There should probably be a small limit to prevent clock stacking, such as allowing only one per chunk or within a certain radius. There could also be a warning message in the middle of the screen when you hover your cursor over the pedestal or the clock saying: ‘This clock is not effective because another one is already nearby,’ or something similar.

**Comment by sinkillerj** [comment]
Honestly, in my opinion and with all due respect, I don’t think you should reply to a random issue from 2017.
