### ISSUE TITLE
Duplicate items displayed in Transmutation Table GUI.

### ISSUE THREAD

**Issue by AshenGaming** [sinkillerj/ProjectE#1642]
**Exact ProjectE version:** ProjectE-1.12.2-PE1.2.0
**Exact Forge version:** forge-14.23.1.2610

**Steps to reproduce:**

1. Place a transmutation table and open it.
2. Put in an item (I used Divining Rod (High) as an example). At this point there is no issue.
3. Place another item with EMC value into the table to learn (I used covalence dust).
4. After teaching covalence dust there will be a duplicate copy of the Divining Rod.
5. Additionally, if you teach a new item while the duplicate is showing, one of the Divining Rods turn invisible in the GUI until you re-open the Transmutation Table.

**What I expected to happen:**

The GUI should show one copy of each item, and should not turn invisible.

**What happened instead:**

The GUI does not show duplicate items, nor do items turn invisible while teaching new items.
![image](https://user-images.githubusercontent.com/5949532/35801425-44318142-0a64-11e8-9063-537e8c0bcea3.png)

**Comment by BenjaminUrquhart** [comment]
Does covalence dust appear in the table while the duplicate item is showing?

**Comment by AlphaKintari** [comment]
I also noticed this in my single player game, but with an iron sword. I will try and duplicate the issue later on, and update with more info.

**Comment by SteveGodwin** [comment]
^ Have also been seeing this problem. It goes away if I disable Astral Sorcery. Looks like Thaumcraft has been seeing a similar bug (linked to above).

**Comment by FoxBotGames** [comment]
I have been able to successfully replicate this but only with Project E Items and occasionally Thermal (Suite) Mod Items. The ones seem affected seem to have a charge bar; so the tools, klein stars, Philosopher's Stone. (Flux capacitor from Thermal Expansion)

If you forget these items the second item learned gets removed HOWEVER the remaining item learned consumes EMC and gives you nothing. So shift clicking these eats all your EMC.

See https://github.com/GrimCo/CoopLife2/issues/46
(This links modpack used in and mod list along with config settings and other required info)

As seen I thought this was already known about and was underway in fixing, for the dupe items in table.
I then tested it myself when I had seen the comment about the EMC being eaten on false items in the table because of this issue.

**Comment by IcemanXChill** [comment]
This is actually a bug playing with just ProjectE alone. (No extramods) Just startup minecraft version 1.12.2, give yourself a transmutation table and two Philosophers stones into it, put them into the transmutation table and viola! two of the item are in the table. 

An image: 
<img width="497" alt="screenshot" src="https://user-images.githubusercontent.com/26318684/45588621-7a14b880-b8e5-11e8-9cf6-3ecb1dd8225c.png">
