### ISSUE TITLE
Klein Star recipe missing and is uncraftable.

### ISSUE THREAD

**Issue by WhisperFire26** [sinkillerj/ProjectE#1712]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.12-PE1.3.0

Exact Forge version: modded forge-14.23.4.2707

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): Game does not crash

Steps to reproduce:

1. Look up the recipe in JEI for Klein Star to craft in survival.

What I expected to happen:
There is a crafting recipe for the Klein Star Ein, but there are no crafting recipes for the Klein Star Zwei, Klein Star Drei, Klein Star Vier, Klein Star Sphere, or Klein Star Omega.

What happened instead:
There are no crafting recipes available for the following items: Klein Star Zwei, Klein Star Drei, Klein Star Vier, Klein Star Sphere, or Klein Star Omega.

I made a modpack featuring your mod. What can I do to correct this oversight?

**Comment by williewillus** [comment]
those do not have JEI recipes because they're "special recipes" - extra code logic is needed to transfer the EMC values over to the upgraded star. The recipe should still work however: four of a lower star in a square makes the higher star

**Comment by Lilylicious** [comment]
This will be fixed in an upcoming release, no ETA yet.

**Comment by Flexico** [comment]
I believe I am having the same issue; I can craft the Klein Stars manually, but they don't work in any kind of auto-crafting unit.

As for the transfer of EMC, that doesn't seem to work at all: I crafted a full KS Zvei with three empty ones, and the resulting KS Drei was empty.

I don't mind the second issue though; as I can easily empty the klein stars into a relay or transmutation table before crafting them.

**Comment by Lilylicious** [comment]
The fix for the EMC transfer is implemented already and should be released in the next release after 1.3.1B unless something unforeseen happens. They will also show up in JEI at that point.

The autocrafting issue I'm not sure will be fixed. The EMC transfer requires them to have their own recipe type, and even if it's just a shapeless recipe with some EMC handling added on to it, autocrafters likely wouldn't recognize it without some integration, which I doubt will be implemented.
