### ISSUE TITLE
[Suggestion] Items with EMC / Covalence Loss that are below 1 should default to zero.

### ISSUE THREAD

**Issue by Lance5057** [sinkillerj/ProjectE#1745]
Maybe make it configurable but at the moment if I have covalenceLoss = 0.25 and I put in some cobble with an EMC of 1, I still get 1 EMC. I think this would be a pretty easy way to counter things like cobble generators pumping out tons of free EMC if the modpack calls for it.

**Comment by sinkillerj** [comment]
Realistically if a pack wants to remove cobble EMC they can just remove the value. If there's enough demand I'll consider such a config, but it seams like a very niche and unnecessary desire.

**Comment by UnstableCodeScarlet** [comment]
A "0" EMC would be nice imo, you can just pull as much as you want out or put as much as you want in.
You could set cobble, stone, dirt, grass, etc to 0 in a skyblock map for example.

**Comment by Lance5057** [comment]
Any update on this suggestion?

**Comment by DemonfangArun** [comment]
> 
> 
> A "0" EMC would be nice imo, you can just pull as much as you want out or put as much as you want in.
> You could set cobble, stone, dirt, grass, etc to 0 in a skyblock map for example.

That would be an interesting idea. You could have it in the table (for convenience), pull out or put in an infinite amount, and not have it affect the actual EMC in the table. This is definitely better than the ideas I came up with, and likely easier to implement.

**Comment by Darkstrumn** [comment]
Hi,

What if items with fractional EMC calculations, rounded down to the nearest whole number (or just truncated the fraction with a floor of 0 to negate the need for rounding maths).
This would allow the item into the table (EMC > 0) would cost to pull from table (1), but burn for less (0).

I have a modpack that's based on tech(RFTools), psi(psi) and magic(ProjectE). 
Given the opening lines of the ProjectE wiki, I wanted users who use magic\\EMC to find ways to power their magic, as stored EMC is finite. So using the tablet to "recycle" junk is fine and encouraged in this pack. However, in the vein of equivalent-exchange, I don't think any item pulled from the tablet should have a 0 EMC cost to negate EMC generation techniques. This seems to defeat the spirit of magic discovery\\journey thing the wiki seems to encourage on how to go about magic... .

The value of junk items can be < 1 EMC, requiring the burning of more items to collectively get 1+ EMC vs the individual item's value. This must be done at once to get the collective payout. The EMC loss can be blamed on the price exacted by the "flame of exchange" aka burning or some such. But, the cost of pulling\\conjuring an object from EMC should never be 0, IMHO.

This could fix calculation differences with items such as glass and glass panes for example: glass defaults to 1 EMC, as does glass panes. However, to craft panes, you need 6 glass and produces 16 panes - the yield is 10 extra EMC. Presently the EMC is likely calculated as 6/16 rounded up to 1 as the viable min. EMC value.

If the fractional EMC were stored per item vs. a whole number, the cost to pull can be rounded up to stay 1 for the cost, but the EMC burn value would be effectively 0 for a single calculated value thats < 1; the burn payout value should round-down\\truncate to 0 EMC, while costing 1 EMC to pull from the tablet. This should fix over-unity unless there is some limitation preventing the storage of decimal, or the expression that would correctly calculate the effective EMC value of an item, as a string.

If the computed value at load time can be stored as the proper decimal value, vs being rounded to integer, then this could work and continue to allow specific EMC values by setEMC and initial computation to work as it currently does.

Just my perspective, but hopefully it makes as much sense to you folk as it does to me. :)

End of line.

**Comment by MaPePeR** [comment]
> Presently the EMC is likely calculated as 6/16 rounded up to 1 as the viable min. EMC value.

As far as I know EMC calculation always rounds down. Glass Panes should have an EMC value of 0, so not transmutable. 

For recipe calculation fractional EMC is already used, so stuff made from glass panes will get the value of the panes added (which is mostly 0, though)

**Comment by Darkstrumn** [comment]
Oh, Ok. I was using an older version I reckon, but in it, glass panes had an EMC of 1.
Even so, if what I suggested is technically in play, why would dirt and the like need to be set to 0?
Or is the focus not that it needs to, but rather a request to be able to? If so, pay no attention to me, as I must have misunderstood the issue. ;-P

**Comment by Lance5057** [comment]
The issue is less about things being zero and more about things having 0 emc not being in the table.

**Comment by DemonfangArun** [comment]
> 
> 
> Oh, Ok. I was using an older version I reckon, but in it, glass panes had an EMC of 1.
> Even so, if what I suggested is technically in play, why would dirt and the like need to be set to 0?
> Or is the focus not that it needs to, but rather a request to be able to? If so, pay no attention to me, as I must have misunderstood the issue. ;-P

It's complex, so misunderstood isn't a good term.

The reason for wanting it is a balance between convenience and preventing easy mass getting EMC. Getting mass amounts of -insert basic building block- is trivial in most packs. This leads to an easy way to pump a crapload of them into a condenser chest and get emc for bulk items. I could take the easy way out and just remove the EMC completely, but this would annoy builders who like having an endless supply (in relative terms) of building blocks at their fingertips.

This is why in #1765 I had a suggestion of manual EMC burn setting (on top of the ratio). You could keep the ratio for most items, but override it for others, essentially allowing further customization. In the end, this whole topic is about adding configuration so that modpack creators can custom tailor mods to fit into a pack in a desirable manner, so if multiple solutions are implemented then the more people can be pleased. It would be great to be able to have project E in a pack and be able to balance it out so it doesn't stick out as a mod that creates a heavy imbalance, I'd like to see it start showing up in more packs, it has great potential, but needs to be tunable.

**Comment by Darkstrumn** [comment]
The player\\tablet doesn't auto-generate EMC; the user must collect it by any and all means, given the vast sums of EMC needed by the more advanced stages of the mod. EMC "generation" seems to be a deliberate mechanic. Why is it bad for folks to find ways to generate EMC via automation, it's a finite resource that must be replenished and requires user interaction to do so?

Users fabricating EMC generators is what the Condenser is used for, it's what it does... . While I'm not  judging, it sounds like it's being suggested that one of the main functions of the Condenser is being looked at as a problem. How, you can't pipe the EMC from it into the Tablet directly, that requires manual action.
Users needing to put in the labor, gives it balance, doesn't it?

Anyway, the config could be setup to allow the following to provide the additional control desired by various Gaming Operations Directors (GODs) and should be "relatively easy" to implement.

1. (Boolean|_true_) Tablets allow items with 0 EMC: This allows items with 0 EMC to be added to tablet. Items in the Tablet with an internal cost of 0 will cost 1 EMC to pull. And cost 1 EMC in build calculations. (I've tested an items that Cost 1 EMC put into tablet. Then set to 0 EMC and the item remained in the tablet, but could not be pulled, nor any more burned until the cost was set back to at least 1 EMC.)
2. (Boolean|_false_) Tablets allow items with -1 EMC: This allows items with -1 EMC to be added to tablet. items in the Tablet with an internal cost of -1 will cost 0 EMC to pull. But cost 1 EMC in build calculations.
3. (Boolean|_false_) Condensers only rely on EMC (Collectors and relays): This turns off\\locks out the condenser from accepting physical matter. Internal storage only holds what is produced (read only if you will).
4. (Boolean|_false_) Condensers are lost techniques: This turns off Condenser recipes so they can't be made
5. (Boolean|_false_) Condensers can be treasure: This adds Condensers to treasure lists; combined with the above, can make them something to dungeon dive for as a limited resource (like a Warhammer 40k OTC ;-P ).
6. (int:1-100|_10_) Chance of Condensers as treasure: This sets the rarity of this treasure type.
7. (Boolean|_false_) Condenser IIs can be treasure: This adds Condenser IIs to treasure lists; combined with the above, can make them something to dungeon dive for as a limited resource (like a Warhammer 40k OTC ;-P ).
8. (int:1-100|_5_) Chance of Condenser II as treasure: This sets the rarity of this treasure type.
9. (Boolean|_false_) book:"Condenser lost techniques" can be treasure: This adds recipe books to treasure lists that turns on the specific Condenser recipes so they can be made (Condenser)
10. (int:1-100|_8_) Chance of book:"Condenser lost techniques" as treasure: This sets the rarity of this treasure type.
11. (Boolean|_false_) book:"Condenser lost techniques II" can be treasure: This adds recipe books to treasure lists that turns on the specific Condenser recipes so they can be made (Condenser mk.II)
12. (int:1-100|_3_) Chance of book:"Condenser lost techniques II" as treasure: This sets the rarity of this treasure type.

**One further new feature idea: (Allows an EMC cap before instability is applied to Condenser EMC storage)**

13. (long(or present datatype)|(value representing MAX for datatype)) Condenser Max EMC stable storage: This would introduce instability once the limit was exceeded. This instability has a random chance of exhausting a random percentage of the stored EMC until the stored amount is under the limit. (note MAX means there is no instability)
14. (long(or present datatype)|(value representing MAX for datatype)) Condenser II Max EMC stable storage: This would introduce instability once the limit was exceeded. This instability has a random chance of exhausting a random percentage of the stored EMC until the stored amount is under the limit.(note MAX means there is no instability)

These options introduce greater control over the mod that may even make the experience more fulfilling than the default, such as making the Condensers lost techniques and treasures that must be found as treasures. 
_Option 2 may be tricky._

These options seemingly would satisfy the compromise of disallowing equivalent-exchange based EMC generators, while not sacrificing the character of the mod (IMHO). 

What do you all think these config options & new feature proposals?

**Comment by Darkstrumn** [comment]
10k+ a second! That's ludicrous speed, I've seem to be doing it wrong! I can see where that would be an issue. I have seen some vids on that when you could condense things into damaged items and repair them. But figured that matter was resolved.

Thanks for clarifying; I don't dump rock on that scale! XD

With option 3 and Equivalent Energistics: EMC storage and condenser systems thate EE automation is capable of, is pretty tech. Does EE use ProjectE API calls to make its condensers work?
If so, changes there may enforce ProjectE configuration rules for condensers across to dependant mods.
If not, then hopefully collaboration can get EE to respect ProjectE config settings (API may need to be able to provide that info for external mods). But, having looked at the mod (https://www.youtube.com/watch?v=TSHZA-yl67U) EE condensers seem to only work via matter exchange (to extract the EMC value from an item). So, if option 3 is true, the API should tell EE to set all item EMC values high enough, that the ultimate condenser is the only one that would effectively work, or high enough to even prevent it from working. But once you have one, are you not "powerful" a magic-user to craft low end items at virtually no cost, and can let them have the ultimate condenser?

This of course concludes that either EMC reading is being done via API, or that the author is willing to read the config info from API and adjust the mod to account for the ProjectE(PE) restrictions.

That video mentions that EE works with Equivalent-Exchange 3 (EE3) also, do you know if PE and EE3 are able to be used together? if So does it also need to account for these changes? (Or am I over thinking it? ;=P )
Would a config setting help control PE to EE interaction by disabling "restricted" features via API and returning data that would not return anything, but not brake the other mods? (is that a thing?)

**Comment by MaPePeR** [comment]
> This is why in #1765 I had a suggestion of manual EMC burn setting (on top of the ratio). You could keep the ratio for most items, but override it for others, essentially allowing further customization. 

This was implemented, but deemed to complex.

**Comment by sinkillerj** [comment]
To add context I wanted to avoid it because that's not the type of mod ProjectE is. When you start adding individual sell values for each item pack authors treat it as a currency mod. That in turn leads to end user confusion, its much easier to explain that on this server you get half the EMC back than it is oh this item you get full EMC, this one you get none, this one you get a forth.

**Comment by DemonfangArun** [comment]
Fair enough point, but as a counter isn't it already even without this? It's your mod, and you have the right to develop it how you please, but I would say the best option would be to add configuration options so that server owners could micromanage as they please, and have the default behavior be to act like it does now). If a server owner wants to tweak it to hell and back then the onus is on them, and not you, when players are confused. Being able to tweak Project E on such a granular level might also lead to wider adoption once pack owners realize they can set it up so that it won't blow a wide hole in any semblance of balance a pack has.

And to MaPePeR: I'm not going to pretend to understand how the mod is coded, but from my high-level perspective I don't see how it's all that much more complicated than the setEMC command and the corresponding custom EMC file. Enlighten me if you wish.

**Comment by tecnobrat** [comment]
I wanted to build a pack around ProjectE and the concept that you burn items for 1/10th their EMC.  However this means that cobblestone is the best item to burn, since it still generates 1:1 EMC.

If I remove EMC from cobble, it breaks EMC for any items that come from cobble, like a furnace (and a lot more).

Right now I'm throwing the idea around of multiplying ALL items by 10x EMC to work around this, that would allow cobble to still burn for 1 EMC but cost 10 EMC.

I agree with @sinkillerj that we don't want items randomly costing / generating random %s of EMC, and unfortunately thats the case now with cobble since it burns at 100% due to rounding up.

**Comment by sinkillerj** [comment]
A config is coming, I forgot in the last update.

**Comment by DemonfangArun** [comment]
Can confirm config option has been added, picked up on it in a config sweep today. Thank you very much :D
