### ISSUE TITLE
Negative EMC - How to only reset EMC Value?

### ISSUE THREAD

**Issue by RealPwned** [sinkillerj/ProjectE#1894]
Hi,
i reched the maximum of EMC now its negative.. any way to reset emc without
reset knowlage too?

Thanks

**Comment by sboys3** [comment]
This also happened to me.  I think that there should ether be a simple check to prevent the rollover or emc should be stored as a float.

**Comment by jonfin2** [comment]
If you have a transmutation tablet you can change the value of an item that has no EMC value to any number by using the command /projecte setEMC "number" and restart or reload using /projecte reloadEMC

**Comment by LoganDark** [comment]
@jonfin2 Nope.

They're saying that if you get too much EMC (by burning incredibly valuable items, or by using, oh I dunno, too many Final Power Flower Bonsai Pots), it'll go negative.

I'd recommend keeping a Final Star from Project EX around to reset your EMC to 0 when this happens.

**Comment by dedphrog** [comment]
Love your mod so far.
This is happening to me as well.

ProjectEX-1.2.0.36.jar
ProjectE-1.12.2-PE1.4.1.jar

In one gaming session i went from having around 150 MK5 bonsai flowers, to replacing them with 150 mk15 flowers, to replacing them with 150 final flowers.

Now my EMC value is in the negative 50% of my server time, making it impossible to craft from EMC tablet during those long windows.
I went through the configs of ProjectE and ProjectEX and saw nothing yet to cap the value before it rolls over to negative values -- or reset it to zero rather than the really big negative value. This seems like a simple thing, could you please add it (or ask projectEX folks too) ?

Thanks!

**Comment by NiSiSuinegEht** [comment]
For servers, especially with the recent spate of packs including both ProjectE and EX, a command to reset a player's EMC to 0 without clearing their knowledge would be very useful.  In Builders Paradise, for example, the Final Star is disabled, and so can't be used, and a single Final Power Flower Bonsai was enough to put me into the negative while I was logged off.

**Comment by LoganDark** [comment]
@NiSiSuinegEht Or they can just, you know, use an unsigned integer, which doubles the maximum EMC value, and overflows to 0, rather than going way negative.

**Comment by pupnewfster** [comment]
Closing this as it was due to another mod bypassing safety checks we had in place and thus breaking when we converted our data (that we had validated to be in a specific range) to a more accurate data type. Additionally ProjectE for 1.14+ now uses a BigInteger for storing player emc.
