### ISSUE TITLE
Crash while adding ProjectE to Dungeons Dragons and Space Shuttles

### ISSUE THREAD

**Issue by Machiavelli1990** [sinkillerj/ProjectE#1926]
Hello :) 
I'm trying to add ProjectE to the latest Version of DDSS, but everytime I add it and load the Pack, it doesn't finish and just gives me a crash log (which can be found in the pastebin)
Not sure if it has something to do with ProjectE itself or if it's a Nuclearcraft issue. Added Projecte to a bunch of packs by now, but never had this kind of issue. Hope you can help me out here :)

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.1B

Exact Forge version:  forge-14.23.5.2836

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/5NtxtRpJ

Steps to reproduce:

1. Add Projecte to DDSS

What I expected to happen: Modpack loading fine and having EMC ingame

What happened instead: Crashes while loading the pack. Not sure if it's ProjectE related or an issue to Nuclearcraft.

Posted this on DDSS github aswell, they told me to come here. So thanks in advanced for helping me out :)

**Comment by sinkillerj** [comment]
Looking over this it appears to be NuclearCraft causing the issue by trying to register values in a incorrect way, this may be an api mismatch caused by the older version of ProjectE you are using. I do not know much about the pack, but as I see it you have a few options:
A. See if NuclearCraft has a config option to disable ProjectE integration.
B. Update ProjectE if possible, this may involve running the pack on a newer Forge.
C. Remove NuclearCraft if you do not utilize it.
