### ISSUE TITLE
How about automatic solution for exploits

### ISSUE THREAD

**Issue by TheK0tYaRa** [sinkillerj/ProjectE#1931]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version : 1.4.1

Exact Forge version: forge-1.12.2-14.23.5.2847

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash occured

Steps to reproduce:

1. Launch minecraft server
2. Close it after world loads
3. Watch logs have things like "[Server thread/WARN] [projecte]: EMC Exploit:"

What I expected to happen:
A link with info about to a way of fixing it manually or automatically appearing

What happened instead:
It ain't there

**Comment by sinkillerj** [comment]
This is at the discretion of the pack author, ProjectE cannot detect all possible exploits, but logs what it can as a convenience, these could contain false positives.

**Comment by MaPePeR** [comment]
Normally these don't contain false positives, but there are not all exploits listed. (It cannot know exploits for machines that it doesn't know the recipes of)
The reason these are not fixed by default is, that they are the result of explicitly set (user or default) values. Exploits that can be fixed without modifying default or user values are already fixed automatically.

To fix them all one would also loose some of the iconic emc values (e.g. gold at 2048 is an emc exploit because of the rounding down when calculating the emc for gold nuggets)

[https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/emc/SimpleGraphMapper.java#L15 This compile time option] fixes them automatically, but is not user-exposed at the moment. (I thought it was, but apparently it isn't)
