### ISSUE TITLE
EMC value cannot be set to zero for items

### ISSUE THREAD

**Issue by teamaonn** [sinkillerj/ProjectE#1938]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 2.0.0 (1.14.4)

Exact Forge version: 28.1.96

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): None available

Steps to reproduce:

1. Hold any item.

2. Type in /projecte setemc 0

What I expected to happen:

Emc set to zero, and item removed from Transmutation Table

What happened instead:

Nothing. There was no change at all. Happened with regular items and NBT items.

**Comment by MaPePeR** [comment]
You need to execute the reloadEMC command separately.

**Comment by pupnewfster** [comment]
> You need to execute the reloadEMC command separately.

For one it would be `/reload` but there is also the chance that this is broken given this is for the 1.14.4 version of ProjectE he compiled himself, and I didn't actually test setting things to zero EMC. So it may be broken given commands had to be rewritten due to a new system MC made for commands.

**Comment by pupnewfster** [comment]
Hmm interesting, it *does* actually work but requires a server/world restart instead of just a `/reload` to make it recognize it. However when changing emc values to things other than zero it properly works off of just a `/reload`
