### ISSUE TITLE
1.14.4 crash on server start up

### ISSUE THREAD

**Issue by SDUBZ** [sinkillerj/ProjectE#1941]
Forge 1.14.4-28.1.99
PE: ProjectE-1.14.4-PE1.0.0B
crash report:
[crash-2019-12-10_06.22.02-server.txt](https://github.com/sinkillerj/ProjectE/files/3941364/crash-2019-12-10_06.22.02-server.txt)

:log:
[latest.log](https://github.com/sinkillerj/ProjectE/files/3941365/latest.log)
[debug.log](https://github.com/sinkillerj/ProjectE/files/3941366/debug.log)

**Comment by pupnewfster** [comment]
Does it happen every time or randomly? I have only seen a similar issue before where a random mod crashes for no reason on startup of a client. I think there is some sort of race condition in forge due to the parallel loading but have not bothered looking into it much. If it just happened once and starting again fixed it then I am going to assume that this is the case and it doesn't actually have to do with ProjectE especially since the stack trace doesn't have anything to do with projecte at all except for the mod it named.

**Comment by SDUBZ** [comment]
i will try like 5 times in a row and check again
and report back okay :)

**Comment by sinkillerj** [comment]
Closing as this version is now very old and no further info was provided.
