### ISSUE TITLE
1.14.4 - can't removeEMC with tags

### ISSUE THREAD

**Issue by Partonetrain** [sinkillerj/ProjectE#1944]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.14.4-PE1.0.0B.

Exact Forge version: 28.1.106

Steps to reproduce:

1. Use /projecte removeemc #minecraft:logs (or any tag)
2. /reload
3. All items with that tag have their default EMC value

What I expected to happen:
All items with that tag have an EMC of 0
What happened instead:
All items with that tag have their default EMC value

Tags work fine with setEMC.

**Comment by pupnewfster** [comment]
@MaPePeR I would like your input on what to do with this. I sent a more detailed question/possible solutions to you on discord, but I believe this is due to the fact that when reading custom conversions for tags (and before for ore dictionary), it also sets the before value for all elements. However when setting a value via the custom EMC file, it doesn't also set it for all elements. This is why you can't easily override the defaults that are from the conversions like that.

You know the system better than anyone, do you think it should have the custom emc also set the elements of the tag, or should the custom conversion thing not set the before value for elements of the tag, or is this behavior intended.

**Comment by pupnewfster** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/projecte/files/2855942
