### ISSUE TITLE
1.15.2 Initializing game crash

### ISSUE THREAD

**Issue by frostfire50** [sinkillerj/ProjectE#1967]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.15.2-PE1.0.2B.jar
Exact Forge version:
Forge-31.1.11
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
 https://hastebin.com/opecikoqij.rbSteps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by frostfire50** [comment]
I messed up

**Comment by pupnewfster** [comment]
Not positive if you had meant to close it or not given you opened it saying you messed up and then reclosed it. But remove optifine. Last I checked for optifine specifically states that it is not compatible with forge yet. But either way this is due to optifine breaking this forge patch: https://github.com/MinecraftForge/MinecraftForge/commit/40de19f16ed4741cbd65483f83c12630188c18cc
