### ISSUE TITLE
[Suggestion] Ignore EMC Covalence Loss config option

### ISSUE THREAD

**Issue by DBPhoenix** [sinkillerj/ProjectE#1980]
Exact ProjectE version: 1.12.2-PE1.4.1
Exact Forge version: 1.12.2 - 14.23.5.2847

Have you considered adding a config for ignoring EMC Covalence Loss in Energy Condensers, so it uses original value instead. I added Covalence Loss to make everything a bit harder and to stop the alchemy table from being an infinite chest, but the EMC Covalence Loss setting hit the Energy Condensers production pretty badly. I hope it can be added to 1.12.2 version too, if it'll ever be implemented.

**Comment by sinkillerj** [comment]
Unless others can chime in with support I personally don't see the value in such a config option.

**Comment by pupnewfster** [comment]
Personally I also don't really see a point, given the whole point of the setting (at least in my opinion) is if you want to have reduced conversion rates. If the condenser didn't get effected by it then you would just convert things via it instead of the transmutation table, just being a bit more of a pain to do so.

**Comment by DBPhoenix** [comment]
That's fair. I primarily used Covalence Loss to prevent the alchemy table from being an infinite chest, but then the Covalence Loss hit the Energy Condensers in a harsh way. If you made an item in the Energy Condenser with Generators with a Covalence Loss at 50%, the value made from generators is essential 25%, if you just wanted to burn it for EMC. Anyway thanks for replying so fast.
