### ISSUE TITLE
Multiplayer Questions

### ISSUE THREAD

**Issue by XiNaru** [sinkillerj/ProjectE#2010]
Good day,

I have two questions about ProjectE.

1. Is it somehow possible for the multiplayer to have an FTB team based EMC? So that both (all) players have the same items and the same amount of EMC?

And 2.
When I put ProjectE on a server, what about the setEMC command? Can only use the OR or how does it work?

**Comment by pupnewfster** [comment]
1. There is no way to share knowledge between players natively in ProjectE. It is possible some addon adds ways to but offhand I am not aware of if any do/what their names are.
2. Not quite sure what you are asking, but the setEMC command works the same on the server as it does in single player (except that it sets the emc value in the server's config rather than your local config).

**Comment by XiNaru** [comment]
1. Okay, understand, that's a shame, but not absolutely tragic.

2. Well, it is about: If I have ProjectE on a server, I just DO NOT want a normal player to suddenly be able to determine the EMC value of objects through the command.

**Comment by pupnewfster** [comment]
Only ops are able to use projecte's commands on a server.

**Comment by XiNaru** [comment]
okay that ist good :) thank you, so i can use the mod without problems :)
