### ISSUE TITLE
Pedestal renders removed item

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#2096]
Exact ProjectE version: ProjectE-1.16.5-PE1.0.0B

Exact Forge version: forge-1.16.5-36.0.14

Steps to reproduce:

1. Remove an item from pedestal
2. Put new item into pedestal
3. Activate pedestal

What I expected to happen:

1. The item that I removed from the pedestal will no longer render on top of the pedestal

What happened instead:

1. After I remove the item from pedestal, the removed item still renders on top of the pedestal (not actually still in there, as its not functional and the removed item appears in the inventory)
2. When putting a new item into the pedestal, the pedestal still renders the old item on top
3. only when activating the pedestal does it start to render the new item

**Comment by pupnewfster** [comment]
Is this on a server or in single player?

**Comment by nayfaan** [comment]
server

**Comment by pupnewfster** [comment]
Not able to reproduce this in either single player or on a server.

**Comment by pupnewfster** [comment]
So while I was testing some other things I was able to *sort of* reproduce this issue, except in reverse... Where it doesn't always render the item that it has in it (rather than rendering an item it no longer has). But I believe the cause is likely the same so I will try and see if I can fix it now that I have a reproduction scenario.
