### ISSUE TITLE
Typing LV In Transmutation Table Crashes The Game With Mod: "LuCraft"

### ISSUE THREAD

**Issue by FoxGerardas** [sinkillerj/ProjectE#2100]
Crash: 
[crash-2021-02-26_14.06.34-client.txt](https://github.com/sinkillerj/ProjectE/files/6049609/crash-2021-02-26_14.06.34-client.txt)

Version: ANY
Fix It As Soon As posibble. I Have Reported 3 Bug Today Because Of Using Mods: Mo' Bends, ProjectE, Lucraft ahhhhhhhhh

**Comment by sinkillerj** [comment]
Can we just like, not be an entitled lil prick? Kthx. Also if you could actually like, provide the full details requested in the future instead of just being like "any"...

Your crash report indicates that you have added a "lucraft" item to your transmutation table, it is causing a crash as the mod does not have code to handle the NBT data of the item being missing. To resolve this crash unlearn whatever you put in then optionally add it to your NBT whitelist.

**Comment by FoxGerardas** [comment]
Oh, ok
.
