### ISSUE TITLE
[1.16.5] Repair talisman damages Astral Sorcery Crystal tools instead of repairing

### ISSUE THREAD

**Issue by LuciusV** [sinkillerj/ProjectE#2102]
Exact ProjectE version : 1.16.5-PE1.0.0B

Exact Forge version:  36.0.39

Steps to reproduce:

1. Equip Repair talisman, make a Crystal Pickaxe from Astral Sorcery celestial crystals (3 size I crystals give 23478 total durability)
Mine something to damage tool: it will start to degrade (but damage stops after some time)
What I expected to happen:
Tool repaired until full durability
What happened instead:
Tool is degrading randomly

**Comment by pupnewfster** [comment]
I am going to go ahead and say this is probably a bug on astral sorcery. The way the repair talisman works is it checks if it a damageable item, has damage, and is repairable. If all those are true it then sets the damage to one less than the current damage value.

**Comment by BlueAgent** [comment]
It's a bit strange that the talisman is working on the crystal tools at all...

Since crystal tools [aren't meant to be repairable](https://github.com/HellFirePvP/AstralSorcery/blob/a6af6c8bd95f49d92acce0bb213e9ec5f931c7ed/src/main/java/hellfirepvp/astralsorcery/common/item/tool/ItemCrystalTierItem.java#L152-L160) and the talisman, afaict, is meant to ignore not repairable items:

https://github.com/sinkillerj/ProjectE/blob/b81e11abbc746fff7e511e383edd6661e61c0a27/src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java#L39-L41

https://github.com/sinkillerj/ProjectE/blob/b81e11abbc746fff7e511e383edd6661e61c0a27/src/main/java/moze_intel/projecte/utils/ItemHelper.java#L194-L196

Are you sure that it's the talisman that's damaging / repairing the crystal tool and not some other mod?

**Comment by LuciusV** [comment]
> Are you sure that it's the talisman that's damaging / repairing the crystal tool and not some other mod?

Yes, because strange durability changes not present if I don't use talisman.

**Comment by BlueAgent** [comment]
Did you test with just Astral Sorcery and Project E installed?

**Comment by LuciusV** [comment]
Could you please tell me what file I should provide, is it .minecraft\logs\debug.log ?

**Comment by BlueAgent** [comment]
Yes, that's the one.

**Comment by LuciusV** [comment]
I also cannot reproduce it in new minecraft instance with only astral sorcery and projectE, and cannot identify responsible mod from modpack.
[debug-1.log.gz](https://github.com/sinkillerj/ProjectE/files/6094109/debug-1.log.gz)
In this test all was as expected...

**Comment by LuciusV** [comment]
I also cannot reproduce it in modpack again. I remember that I was wearing prism with some enchantment but I recrafted that prism and don't remember what it was. So I assume this report can be closed.
