### ISSUE TITLE
missing emc value - vanila items

### ISSUE THREAD

**Issue by gendalv** [sinkillerj/ProjectE#2103]
shroomlight, chainmail, stone slab

**Comment by pupnewfster** [comment]
I will look into assigning a value for shroomlight next time I am working on ProjectE but yes chainmail has no EMC value as it has been historically made from fire which has no EMC value, though given there has been more ways since to get chainmail I may look at adding a value for them. In regards to stone slabs those can't have an EMC value as that value is less than one.
