### ISSUE TITLE
emc dupe

### ISSUE THREAD

**Issue by RoHarV** [sinkillerj/ProjectE#2131]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:_1.16.5-forge-36.1.4_

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. _take 1 clay block_ 
2. _place block and break_
3. _put clay balls into EMC table_

What I expected to happen: 
_I expected clay blocks to be 64 EMC_ 
What happened instead:
_breaking the clay block will give 4 clay balls so you have created an extra 63 EMC from 1 EMC clay block_

**Comment by pupnewfster** [comment]
If clay blocks are 1 EMC that just means another mod or the pack changed things so there is a recipe that can create clay blocks from 1 EMC. Either manually set the clay block EMC value to 64 so that it doesn't get automatically calculated or live with it or disable the adjustments. If I had to guess Mekanism might be causing this due to the dirt + "water" -> clay recipe in the chemical injection chamber.

**Comment by RoHarV** [comment]
thank you for this information and I hope many great things for you
