### ISSUE TITLE
Question about EMC API

### ISSUE THREAD

**Issue by mcenderdragon** [sinkillerj/ProjectE#2137]
MC: 1.16

Is it possible to register EMC value for items of my mod via the InterModComms ? I would exoect registering works via a pair of ResourceLocation & an int as value?

What I am asking is basicly if there is a version of https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/main/java/moze_intel/projecte/impl/IMCHandler.java#L37-L39 but with soft dependencyies, right now I would need a hard dependency for this API.

**Comment by pupnewfster** [comment]
I am pretty sure it can be done via a soft dependency (you would just need to offload the actual IMC call to another class if the mod is loaded, [for example](https://github.com/mekanism/Mekanism/blob/v10.1/src/main/java/mekanism/common/integration/MekanismHooks.java#L54-L56). The above registers custom NSS types but the concept is the same for how it would be done for that custom EMC call.

Though I might recommend adding the values via a datapack instead of via IMC, in the same way that ProjectE (and Mekanism) set defaults for their values. Example datagen providers can be found [here](https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/datagen/java/moze_intel/projecte/common/PECustomConversionProvider.java) and [here](https://github.com/mekanism/Mekanism/blob/v10.1/src/datagen/main/java/mekanism/common/integration/projecte/MekanismCustomConversions.java). The outputs of those are [here](https://github.com/sinkillerj/ProjectE/tree/mc1.16.x/src/datagen/generated/data/projecte/pe_custom_conversions) and [here](https://github.com/mekanism/Mekanism/blob/v10.1/src/datagen/generated/mekanism/data/mekanism/pe_custom_conversions/defaults.json).

Also while you are here/asking questions, I figure I may as well mention how custom recipe mappers can be done if you have any custom recipes. If you have more advanced mappers/"recipes" that are not `IRecipe` + `RecipeType` based there are some examples in [this](https://github.com/sinkillerj/ProjectE/tree/mc1.16.x/src/main/java/moze_intel/projecte/emc/mappers) package, if you do have custom recipes that are `IRecipe` + `RecipeType` based you can use a more filtered styled mapper, which there are some examples of in [this](https://github.com/sinkillerj/ProjectE/tree/mc1.16.x/src/main/java/moze_intel/projecte/emc/mappers/recipe) package and in [this](https://github.com/mekanism/Mekanism/tree/v10.1/src/main/java/mekanism/common/integration/projecte/mappers) package.

**Comment by mcenderdragon** [comment]
so `data/<modid>/pe_custom_conversions/defaults.json` is enough, awesome, something like this is what I was looking for. I have crafting recipes (shaped & shapeless) which are vanilla but with a research requirement of the player. You need an item before you can create it right? So handling that like any other recipe should be fine I guess, since you cant cheat around the research.

**Comment by pupnewfster** [comment]
Yes, that would be enough (the file doesn't even need to be called defaults, it can have some other name if you have one you would rather use). And yes that probably would be fine for how the other recipes are done, if you *really* wanted to you could use events to deny those items from even being able to be learned/created via EMC until the research is done, though personally that strikes me like that may be overkill.
