### ISSUE TITLE
EMC value generation Incorrect

### ISSUE THREAD

**Issue by Nithlus** [sinkillerj/ProjectE#314]
Hi, I'm not sure how or why. But some items from other mods are generating very low EMC values. An example is the Iron chest mod. The iron chest is made up of a vanilla chest and 8 vanilla Iron ingots, which all have EMC values by default, but the value of emc calculated for the Iron chest is the same as a vanilla chest and ignores the value of the iron Ingots in the recipe.

Do you know why this would be happening?

Also I have tried adding a Custom value for the chest using the config but that does not seem to be able to overide the auto generated one.

Could you make it so that custom EMC values are prioritized over auto generated ones when they are available?

**Comment by DigitalLunacy** [comment]
Kinda old topic but yes, most of the time its a object in the recipe that has no value, or has a lower than normal value because of a recipe change usually involving a mod. best bet is use minetweaker and disable all but one recipe you like for the item, and make sure all the items have a value set by using the command provided with the mod(PE)

i had a mod that let you make wither tools for example so by them adding a recipe for combining a nether star with a wooden item it made every thing that used the wood item 25x more than its normal value lol i just disabled that item in the mod and its was fixed.

**Comment by MaPePeR** [comment]
With PR #363 some of these issues should be fixed (There should only be wrong emc values for Items that have a smelting and a crafting recipe, now...)
