### ISSUE TITLE
Scroll wheel sends item into table, does not reduce quantity held

### ISSUE THREAD

**Issue by itanshi** [sinkillerj/ProjectE#318]
0.2d-dev11 via Resonant Rise 3 latest

**Comment by MaPePeR** [comment]
i found out what is causing the 'scrollwheel'-desync in the transmutation gui.

Nei has a `FastTransferManager.findShiftClickDestinationSlot`-Method that simulates putting something into the gui to find the slot...
this calls transferStackInSlot, but creates a copy of all the itemstacks in the inventory beforehand.
Because `emc` is not stored in a slot it cannot 'revert' the emc changes we make in `transferStackInSlot`.

maybe store `emc` in a hidden slot in the inventory?

**Comment by williewillus** [comment]
Was this ever fixed? I just reproduced it on latest master

**Comment by Kolatra** [comment]
I don't think it was ever attempted to be fixed.

**Comment by williewillus** [comment]
Does this happen with something like AE2 and how do they fix it I wonder

**Comment by MaPePeR** [comment]
I attempted to fix it, and have a very clear idea of what is causing it, but I can't find a good way to fix it. 

It's caused by NEI simulating a slotClick but only client-side. It then tries to determine which slot the items did go into. But our slotClick has the side effect of not only altering the inventory, but also altering the current emc value of the table. 
NEI makes a backup of the slot contents and writes the old content back, after that simulation. 

The only fix I can think of is storing the "current emc" value in a hidden container/inventory slot, so NEI can rollback that value. But that feels very dirty and would only prevent the desync and not make the scrollwheel actually work like it should: because the consume slot instantly consumes NEI can not figure out where stuff went, so it would disable that feature.

**Comment by MaPePeR** [comment]
Did it.
