### ISSUE TITLE
[Request] More general API hooks for EMC values

### ISSUE THREAD

**Issue by ReikaKalseki** [sinkillerj/ProjectE#373]
While Project E currently has a way for mods to add custom EMC values for their items, it is on an ItemStack-by-ItemStack basis. It is thus rather inoptimal if one wishes to assign the same value for all permutations of an item, as the mod needs to manually register every single possible metadata of that item.

I would very much like to see an item-by-item implementation as well, and if possible, a mod-by-mod one (using the modid String) as well, as that would mean I can cut the IMC message count from several thousand to a hundred or so, or even six with the mod-by-mod calls. As you may imagine, several thousand IMC messages, even if the game can handle it without erroring, are not going to be performant.

**Comment by Kolatra** [comment]
Bringing this back up as Reika is blacklisting his blocks and items from having EMC values, which makes sense, however with the way it's being done, and the only way possible, it creates a very long load time with Reika's mods and ProjectE, usually being 10 minutes+.

**Comment by ReikaKalseki** [comment]
Which is why I asked in the first place.

**Comment by Kolatra** [comment]
I will bring this up with sinkillerj whenever he's on IRC.

**Comment by MaPePeR** [comment]
In  most mods you have these mod specific items, that you need to craft for all the things like machine casings or capacitors. It should be enough to remove the EMC from these. 

personally I don't like the idea of mods removing their own emc values. That should be up to the pack author. 
The easiest way to remove emc from all the items is writing a custom `IRecipe` implementation like ae2 does. In the graphmapper I plan to have pluggable implementations for these and allow to disable them with a config.

**Comment by malice936** [comment]
ReikaKalseki not sure if you remember me, I'm one of StrayMavs mods on Twitch, and I've talked to you about perms for a few of your mods in the past. From my experience with ProjectE and its devs what you're asking for just seems a bit unfeasible. There already is an item by item implementation through the configs if I'm reading what you're asking for correctly, however basing EMC on a mod basis is a tad extreme, that's like asking them to hunt down every mod and see what breaks in each one. You can understand why that's a little unreasonable considering that you've went through the trouble of setting up your mod permissions the way you have to avoid a mess like that? If you get the time I would suggest hopping into their esper channel and talking this over with them they are nice people, and I know you are a nice person your self. ^.^

**Comment by ReikaKalseki** [comment]
> There already is an item by item implementation through the configs if I'm reading what you're asking for correctly, however basing EMC on a mod basis is a tad extreme, that's like asking them to hunt down every mod and see what breaks in each one.

That is not what I am asking; there is nothing on your end you need to maintain.

Currently the API requires a mod register a custom EMC for every ItemStack individually. There is no way, within the code, for a mod to say "all variants of this item have this EMC value", zero or otherwise.

As for the mod flag, it is no different from the existing system; a mod would just say "every item from me has this EMC value", which would in my case (and most cases using this option), be zero, but could theoretically be anything.

All it needs on your end is a few new IMC messages and a couple more data structures.

**Comment by malice936** [comment]
Reika, I mean this with all due respect, but if you're going to complain about a mod you should learn that one of its central features is recipe based EMC. In other words you take the root items from your mod and set the EMC to 0 that would cut the EMC from every item in your mod, and reduce the lag significantly. Overall this should be covered by your mods permission list anyway, asking them to change their mod to suit yours will only keep people calling you the "Other Gregtech" and I'm pretty sure that you don't want that.

**Comment by MaPePeR** [comment]
> Are you familiar with RC? Adding EMC values to its items means you can skip to the end of the RC techtree, which is an extremely serious balance problem that historically cuts server life to a time measured in hours.

No i'm not familiar with RC at all, but If the end of the RC techtree ends the 'server life' there is something wrong with RC. (maybe i did read that sentence wrong?)

By default we are probably not adding any EMC values to any RC items because, i assume, these need special machines to create them. We only add EMC to items that are vanilla-smelted or vanilla-crafted from items, that already have EMC. 
If someone uses the configuration file to add EMC to RC items its ones own fault that his 'server life time' is measured in hours.

Adding EMC to Items for all their metadata variants or whole mods has been requested multiple times and will probably happen at some time in the future.

The metadata part is a problem though because the in way the ProjectE is written right now we have to separate items by their metadata values and changing that would probably result in changes in basically every class of ProjectE.
Also there is no way to get a list of valid metadata values for an item in minecraft. (or not that i would know about any - and if there would be one it would create a lot of fake items, for tools that use metadata for damage values)

**Comment by ReikaKalseki** [comment]
> In other words you take the root items from your mod and set the EMC to 0 that would cut the EMC from every item in your mod

> By default we are probably not adding any EMC values to any RC items because, i assume, these need special machines to create them. We only add EMC to items that are vanilla-smelted or vanilla-crafted from items, that already have EMC. 

I was told that EE and Project E both allow for the fabrication of every item in the game with autogenerated EMC values, meaning if you pumped in enough diamonds or other high-value items, you could have it pumping out premade Extractors, Jet Engines, Bedrock tools, and so on. (Even worse with ChromatiCraft, making Crystal Pylons).


> Overall this should be covered by your mods permission list anyway, asking them to change their mod to suit yours will only keep people calling you the "Other Gregtech" and I'm pretty sure that you don't want that.

All I am asking for is an API hook to more efficiently accomplish the same thing I am now, that being make sure that Project E does not allow for the production of RC items.

> No i'm not familiar with RC at all, but If the end of the RC techtree ends the 'server life' there is something wrong with RC. (maybe i did read that sentence wrong?)

Endgame RC is extremely powerful and can be extremely destructive if it fails (and a few machines are destructive in their intended operation). Normally this is not an issue because it takes a very good understanding of RC and a lot of progression to make it to this point. However, as soon as you can shortcut to the endgame via another mod, you get both players who have no idea what they are doing making fission reactors (hope you like Chernobyl) and commonly griefers as well, because while they lack the patience (and often brainpower) for using RC properly, they can easily spam diamonds into a machine that pumps out railguns, ammunition, and jet engines to run it.

> If someone uses the configuration file to add EMC to RC items its ones own fault that his 'server life time' is measured in hours.

A recurring theme with me is people screwing up their own packs and servers and then chewing me out as a result, with many starting rumors, several of which currently persist. My strategy has been to take away their ability to make such mistakes.

> The metadata part is a problem though because the in way the ProjectE is written right now we have to separate items by their metadata values and changing that would probably result in changes in basically every class of ProjectE.
Also there is no way to get a list of valid metadata values for an item in minecraft. (or not that i would know about any - and if there would be one it would create a lot of fake items, for tools that use metadata for damage values)

Maybe set up a matcher that specifically looks for ItemStack objects with a metadata of OreDictionary.WILDCARD which matches any other metadata?

**Comment by MaPePeR** [comment]
> I was told that EE and Project E both allow for the fabrication of every item in the game with autogenerated EMC values, meaning if you pumped in enough diamonds or other high-value items, you could have it pumping out premade Extractors, Jet Engines, Bedrock tools, and so on. (Even worse with ChromatiCraft, making Crystal Pylons).

This is true, but we probably don't have autogenerated EMC values for RC stuff anyway because - like i said: we only use vanilla crafting, vanilla smelting and some defaults for vanilla items to autogenerate EMC values.

> Maybe set up a matcher that specifically looks for ItemStack objects with a metadata of OreDictionary.WILDCARD which matches any other metadata?

Yea, but Maps are not that good with Key Types, that don't implement the `equals()` and `hashCode()` conventions. :/

**Comment by ReikaKalseki** [comment]
> Yea, but Maps are not that good with Key Types, that don't implement the equals() and hashCode() conventions. :/

You can write a wrapper like I did. Just make it pass on most of the important functions (of which there are only 15 or so), or allow for a getItemStack() function (or both), and then add your own hashcode() and equals(). You will have to deliberately invoke hash collisions, though.

**Comment by MaPePeR** [comment]
Yes, we have such a wrapper, but it gets very weird, when you use that as a key for a  hashmap when you implements the `OreDictionary.WILDCARD` logic you suggested. 
Because `wildcard.equals(a) && wildcard.equals(b)` but not `a.equals(b)`.

**Comment by ReikaKalseki** [comment]
> Yes, we have such a wrapper, but it gets very weird, when you use that as a key for a hashmap when you implements the OreDictionary.WILDCARD logic you suggested.
Because wildcard.equals(a) && wildcard.equals(b) but not a.equals(b).

See my edited reply about making a custom map object. You can then override "contains() at will".

**Comment by MaPePeR** [comment]
if something has no EMC(=0) everything that uses this in a crafting or smelting operation will also not have EMC. 

We DO NOT just add up all the numbers and if something has an EMC value of 0 assume that its free. 
If there is something with EMC=0 in a crafting recipe the crafting result will also have EMC = 0.

**Comment by ReikaKalseki** [comment]
In that case, I may not need to blacklist every item, no.

**Comment by MaPePeR** [comment]
Yes, i agree, that this option would be useful. 
I tried to give you something, that can help you right now instead of later, when that option exists.
Blacklisting 30 items instead of 1000 should be a huge improvement.

**Comment by TomeWyrm** [comment]
How does Project E handle conflicting EMC registrations?

More specifically, how does it determine precedence, or does it at all? Can you have EMC conflicts? Do those crash?

Yes, this is related to this issue. I'm trying to be circumspect so as to not give anyone an idea unless they already had the capability to both formulate the idea and implement it on their own. I also don't understand Java enough to just investigate myself and keep this completely circumspect.

**Comment by MaPePeR** [comment]
you cannot have EMC conflicts. it probably just accepts the value that is added in last.

**Comment by ReikaKalseki** [comment]
You might be able to try and ensure that mods can only register their own items (ensure a match between getActiveModContainer() and GameRegistry.getMod() or whatever their names are)

**Comment by MaPePeR** [comment]
@ReikaKalseki another thing you might not be aware of about ProjectE, which I probably should have mentioned earlier: even if we would assign EMC values to all RC items: if you are not using *our* late game item, which teaches you every item with EMC, you would still need to "learn" the items before you can create them from EMC.  Which means you would have to go through the manual process of creating them even with ProjectE. (create one, teach it, buy more of them, proceed with next material) 

Our lategame item is rather expensive.

**Comment by TomeWyrm** [comment]
Something you should probably note about Reika.

It doesn't matter how expensive it is, if you can circumvent his progression, it's not good and he's going to try and break it. I know precisely how expensive the Alchemical Tome is, and it being even possible to get something as innocuous-seeming as tungsten makes it Public Enemy #1 for him.

He's had issues with users in the past whom... well, lets call them derps and move on (Go to his MCF thread and read the What Not To Do section. It's impressive). Unfortunately because of the design philosophy of his mod and the power and destructive capability of his late game, he strictly enforces his tech progression tree. Which is one of capability and understanding, not raw materials.

His main mods are VERY powerful, and so he goes to great lengths to insure that the only people who can get access to that stuff have spent a reasonable amount of time and effort demonstrating their knowledge and understanding of the mod mechanics getting there.

The expense isn't an actual hurdle, I can make a turtle that could get me the alchemical tome just by AFKing before I go on vacation or something.

But at least he now knows that he can break easy compatibility by blacklisting 30 items instead of 481,041 of them.

=========================

Incidentally, if the commands can override the IMC assignment, this entire exercise is moot. Because after the game boots up I can just go "/projecte_setEMC rotarycraft_item_compacts 3 1" and bedrock alloy ingots will get an EMC value of 1.

So while I admire you trying to protect users from the stupidity that has become expected surrounding your mods, at this point it's only harming your reputation for little to no real gain beyond doing absolutely nothing (your items aren't registered by default, hence having null EMC values, and making anything made from them have a null EMC value) because having the registration spam has actually brought attention to the issue, which has probably given people who never would have thought about this before the idea that they could now bypass the tech tree, and that is laughably easy with the commands already in the mod.

I would also encourage you to not intentionally make the mods incompatible either. All that's going to do is engender a LOT of negative attention by making your mods even more restrictive than they already are, and punishing users that will never in a million years think of exploiting your tech gates.

**Comment by ReikaKalseki** [comment]
> Incidentally, if the commands can override the IMC assignment, this entire exercise is moot. Because after the game boots up I can just go "/projecte_setEMC rotarycraft_item_compacts 3 1" and bedrock alloy ingots will get an EMC value of 1.

Would it be too much to ask that blacklisted items not be reconfigurable/overridable with configs or commands?

**Comment by MaPePeR** [comment]
I highly recommend to all the people doing the `/projecte_setEMC rotarycraft_item_compacts 3 1` thing to switch into creative... that should have basically the same effect.

**Comment by ReikaKalseki** [comment]
Agreed, but almost by definition people doing this are unreasonable and have to be actively prevented from breaking everything.

**Comment by TomeWyrm** [comment]
The issue is that it's not really a blacklist, you just set the cost to 0. It's functionally similar but an important distinction. 

Part of the beauty of Project E is the configurability, it makes the mod significantly more useful in modpacks, and especially lets you fix loops and exploits without breaking the game for people that don't know about it or can't exploit it (think the macerator blaze rod loop from EE2)

**Comment by Kolatra** [comment]
Reika, I tried replying to you on TeamSpeak, was not able to.

**Comment by TomeWyrm** [comment]
Now the ability to blacklist things from the Tome? THAT might be a good idea, not just for balance, but for pack makers and such.

I mean you can bypass a lot of the FTB pyramid map if you've got a lot of spare time to dedicate towards EMC generation multiplication so as to get a tome. It only required the 6 (a pair of all 3) covalence dusts, a book, and two fully charged omega klein stars right?

**Comment by sinkillerj** [comment]
I was unaware that the tome had a crafting recipe, one of those fragments from when Moze was working on the mod, I'll make that a config option that is off by default.

**Comment by sinkillerj** [comment]
Oh, and also I do want to add a knowledge blacklist in the near future so no worries there.

**Comment by TomeWyrm** [comment]
Don't make it impossible to end user configure though please. I can easily foresee an addon author doing something just as stupid/malicious as any pack maker and blacklisting iron or some such nonsense. Having to use an end-user IMC mod just to un-derp your game because a mod author or pack maker overextended their "authority" is seriously not fun.

**Comment by ReikaKalseki** [comment]
My suggestion about only allowing mods to blacklist their own items fixes this.

**Comment by TomeWyrm** [comment]
Then the issue becomes is it the mod author's game, the pack maker's game, or the player's game. I'm fine with it being disabled by default, but literally the core concept of Equivalent Exchange was the ability to turn "useless" resources into useful resources with a reasonable exchange rate, and only after you had obtained them legitimately.

What currently exists with no interaction from you is your items do not exist to Project E. But anyone can make them exist to Project E even with your current blacklist ability, and (at least to me) the ability for anyone to say I can't do something with a mod that isn't theirs is the height of arrogance. Make it difficult if you want, but if I want to play with an "exploit", it's my game, and therefore my  perogative. If I play with Project E, I expect to be able to eventually turn my diamonds into bedrock ingots. With the way the mod works right now that would require me to manually assign values. I would think it would make more sense to assign them values you find reasonable rather than trying to ban them outright.

It strikes me like banning your steel blocks from becoming microblocks, or making your items disrupt blood altar construction, or making your nuclear reactors kill botania flowers in a radius, or having your bedrock tools not drop other mod machines. What is the point in breaking compatability with another mod when your mods aren't compatible when there isn't any exploits that the player (or pack author) didn't make themselves?

**Comment by ReikaKalseki** [comment]
> If I play with Project E, I expect to be able to eventually turn my diamonds into bedrock ingots.

You may be reasonable. Most people are not.

> It strikes me like banning your steel blocks from becoming microblocks

What??? I explicitly added microblock support for them.

> making your items disrupt blood altar construction

???

> making your nuclear reactors kill botania flowers in a radius

Radiation kills plants, including those from Botania. I do not specifically target them nor does a nuclear reactor normally do anything at all.

> having your bedrock tools not drop other mod machines

????

**Comment by TomeWyrm** [comment]
It's a metaphoric comparison. It's also getting off topic. I'll try and contact you on TS or IRC tomorrow. I can tell this is going to be a long conversation.
