### ISSUE TITLE
Infinite EMC exploit with Metallurgy

### ISSUE THREAD

**Issue by mysticpoisen** [sinkillerj/ProjectE#422]
Cross mod exploit, if you have Metallurgy installed, Vulcanite ingots have an EMC value of 128, yet two of them combine to make a blaze rod worth 1,536 EMC. A simple condenser/autocrafting setup yields infinite EMC

I found this in 0.2d-dev13 though according to the changelog it hasn't been fixed.

**Comment by sinkillerj** [comment]
We have no way of ensuring that all mods will have acceptable EMC values by default, when introducing another mod you may sometimes need to set a custom EMC value for its items.

**Comment by isochronous** [comment]
@mysticpoisen - I have ProjectE and Metallurgy 4 installed, and none of the Metallurgy metals/resources have EMC values by default.  I've set some values myself, but I'm curious to know what the generated values actually were, because I suspect some of mine are way off (for example, I set magnesium to have an EMC of 512, because magnesium burns with such strong energy, but throwing all of the magnesium I got from one small quarry into the table gave me like 30 million EMC).

**Comment by Robotia** [comment]
@mysticpoisen Are you serious...just do `/projecte setEMC ###` for the item. It's that easy.

**Comment by isochronous** [comment]
@Robotia I'm guessing he reported this as an issue because he thought that all installs should get the fix, not just his.  Either way, this ticket was closed a year ago - the only reason I posted in it is because it's one of literally three relevant results when I searched for "Metallurgy EMC Values", and github doesn't have any private message functionality that I know of.

**Comment by Robotia** [comment]
@isochronous Ah, my bad, I completely ignored the 2015 after the January bit.

**Comment by MaPePeR** [comment]
@isochronous I don't know much about Metallurgy, but if its Alloys you could create a customConversion-Config file for the Alloys. That would then show you 'what the generated values should be'.

>  but I'm curious to know what the generated values actually were

Well - there are no emc values that are generated and not 'there'. So you are curious about something thats not known.
