### ISSUE TITLE
Not assigning EMC

### ISSUE THREAD

**Issue by partytown** [sinkillerj/ProjectE#502]
I have assigned EMC to several items from IC2 but the mod isnt assigning any emc values in further crafting recipes. all the items in the recipes have an EMC value but i wont do anything. restarting wont work and the reload commont wont either.

**Comment by MaPePeR** [comment]
yes, thats probably because IC2 (like AE2, TE and other mods) does probably use a custom implementation for `IRecipe` which we don't understand.

I'm currently working on an architecture that makes it easier to add implementations for these, but this will take more time until its finished and if you don't plan on writing an [`IRecipeHandler`](https://github.com/MaPePeR/ProjectE/blob/integrateGraphMapper/src/main/java/moze_intel/projecte/emc/mappers/CraftingMapper.java#L74-L78) for IC2 will probably not come with the support for IC2 right away.

**Comment by partytown** [comment]
i dont know why i typed IC2 btw, i meant AE2 :P. but okay i understand. thanks

**Comment by sinkillerj** [comment]
Closing as this issue is related to the old mapper, it has now been replaced with the GraphMapper.
