### ISSUE TITLE
BoundsException: 0

### ISSUE THREAD

**Issue by atsivertes** [sinkillerj/ProjectE#509]
Not sure, what exactly happened, but on my server i have Auto Shutdown plugin, which i sheduled to restart the server at 00:00, i am guessing when the plugin tried to stop the server, projectE interfered cause the crash happened at exactly 00:00:00.

Not sure who's problem that is just reporting this. Crash Report https://gist.github.com/atsivertes/0b6d1dfd604f4e4d951a

**Comment by atsivertes** [comment]
Tried forcibly to restart the server via that plugin, an exact crash happened.

**Comment by sinkillerj** [comment]
Cauldron has been abandoned by its creators and there are no plans to add special code to support it at this time. Plugins will likely be supported in 1.8 as there is a new standard which will be builtin to Forge. It's also worth noting that the plugin you are using is doing some odd things, id suggest setting up a external scheduled restart instead of relying on a plugin, if you are using a server manager such as Multicraft it has builtin support for scheduled tasks.
