### ISSUE TITLE
Mod Conflict causing massive infinite loop of death

### ISSUE THREAD

**Issue by rmallo** [sinkillerj/ProjectE#516]
Extra Utilities ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443963-extra-utilities-v1-1-0k ) has an item - the Unstable Ingot - that explodes if left in inventory too long. You can make stable, non exploding ones, and these can be transmuted, but if you create one via transmutation, it becomes an unstable, exploding one again. 
What's worse, if it somehow gets into one of your alchemical bags (Such as if a Black Hole Band sucks it in), it will cause rapid explosions that will kill you any time you pick up the bag. It won't kill you instantly, giving you enough time to open the bag and remove it, but for some reason even that becomes difficult - trying to scroll to it on your hotbar makes the selector jump away from it - Ie, scrolling down onto it on slot 8 makes it jump back after slot 7. I had to fix this by mashing the 8 button and right clicking. 
I apologise about reporting this as it's not DIRECTLY the fault of Project E on its own, but I feel it's too big an error to ignore, especially if someone manages to weaponise this in multiplayer.

**Comment by Tencao** [comment]
This error is more to do with incorrect setup than the mod. This can easily be fixed by simply removing the emc value from unstable ingots, as well as anything else that may cause issues, that's why the config is there. As for the dropping into a bag and exploding, that honestly should be reported to the mod dev of extra utilities than this one, as it's a problem with his unstable ingots.

**Comment by MaPePeR** [comment]
Tencao is totally right. The more interesting question about this is: 
I assume Unstable Ingots have a default EMC value, because we don't consider items that don't leave the crafting grid during the EMC calculation. 

The crafting Recipe is Sigil + Iron + Diamond, but the sigil is not consumed, so we only look at Iron + Diamond and add an EMC value for the unstable ingot, even if the Sigil does not have an emc value. 

I might think about a way to maybe fix this behavior. Maybe do something like 1 Iron, 1 Diamond and 0 Sigil as a Recipe, so the unstable ingots emc still depends on, but is not influenced by the emc of the sigil.

**Comment by artman41** [comment]
I've managed in the latest versions to make stable unstable ingots with transmutation table. did you not feed it stable ingot first?

**Comment by rmallo** [comment]
I did give it a stable ingot at first. Ill try it again later on.

**Comment by sinkillerj** [comment]
Should be fixed by the latest version.
