### ISSUE TITLE
Feature request: don't use ghost items

### ISSUE THREAD

**Issue by septIO** [sinkillerj/ProjectE#523]
when you want to convert items in the condensers it uses a ghost item. Could this be changed to use an actual item? Then you would actually be able to automate switching of items condensed,

**Comment by MaPePeR** [comment]
There was a poll on this and the ghost slot won. Also if there would be a normal slot you would not be able to automate it like this, because you normally don't want anything to extract from the target slot. (transfer node on the chest should not extract from it, so it has to be unextractable or only be accessible from a certain side, which would be unexpected behaviour,if you cannot normally extract from all the sides.)

**Comment by septIO** [comment]
If you go back to the old tekkit days, it was normal behaviour for machines to take an input from the top, and output to the sides. I can't see the problem doing that here? I don't see the condensers as a chest, i see it as a machine, and should therefore (in my opinion) behave as such.

**Comment by MaPePeR** [comment]
Yes, we already allow input into the top, but how to decide, what should go into the target slot and what not? How to decide, when to extract from the target slot and when not? 
It is rendered like a chest, so it is expected to have a similar side - ness: input from everywhere, extract from everywhere.
