### ISSUE TITLE
learned items cycle off the whole list

### ISSUE THREAD

**Issue by Prophious** [sinkillerj/ProjectE#535]
basically when i keep adding in new items into the table(t) eventually i would lose it, more than what you can see ofc, it is like some 200+ or so items like i have stone learned, then over time i lose stone as a learned item even when i search for it

better example is for manulyn for tinker construct, now i had the block learned from the start, but now its not in there, i search for "block" and "man" and there is no manulyn block in there, good thing i had the ingots still learned

anyways the version that it is doing that is ProjectE-1.7.10-PE1.2.0, it may be fixed or increased in new versions, but i would like to atleast let you know about it if you didnt know

**Comment by Aiur850** [comment]
You don't actually "loose" the item. The transmutation table/tablet still has it learned. The issue is when you have ProjectE along with mods that add a lot of blocks with the same or nearly same EMC values. The way the transmutation tables filters items and only shows one page worth is the issue.

I play on a couple servers that have ProjectE installed along with a lot of other mods. When your transmutation table learns too many items, especially if you provide it with a Alchemical Tome(Tome of Knowledge in newer versions or ProjectE) it simply cannot display all the items. For example on one of the servers I play on, I used an Alchemical Tome on my table. No longer can I simply search for and get regular cobblestone,glass,sand etc. It simply finds other items of similar names because only so many items show on the page in the table.

What needs to be done is to change this to allow either exact Item searching by either name or ID(Maybe by using quotes around the names for exact match) or adding pages to the table that we can search through until the item is found. This would be helpful great when this issue gets addressed.

Lastly, it sure would be nice to have an easy way to clear the text in the search box like you can in NEI search by simply right clicking in it.

**Comment by Prophious** [comment]
well i did find out that the server changed some emc values during game play and it just seemed like that i lost some specific items, but now i understand it, maybe a different layout for the items to allow more to be shown at once
