### ISSUE TITLE
Ore EMC value 0 issue after update to PE1.4.0

### ISSUE THREAD

**Issue by Zartach** [sinkillerj/ProjectE#553]
In the latest build (ProjectE-1.7.10-PE1.4.0) blocks of ore can be stored into the Transmutation table with a value of 0 EMC. This leads to an issue where players can get free ore and then mine/smelt it to get free EMC.

I fixed this issue by changing the config option: 
        B:blacklistOresAndDusts=true
to:
        B:blacklistOresAndDusts=false

I did upgrade from a previous build, and that might have caused the issue. But as the config option has the follwing text: 

Set EMC=0 for everything that has an OD Name that starts with `ore`, `dust` or `crushed` besides `dustPlastic` [default: true]

I thought it interesting that by enabling the emc values they now no longer show EMC=0 on the tooltip and can no longer be stored or even put into the transmutation table.

**Comment by MaPePeR** [comment]
The problem solving, that every initial EMC value made it into the EMC map. The blacklist option explicitly sets the EMC to 0. But it should have removed the items from the map, because the values in the map are considered valid emc values, so no EMC = no entry in the map. 

Disabling the blacklist removed the explicitly at values. And as there are no recipes for creating ore they don't get a value. 

Anyway. 1.4.1 is out and has this fixed.
