### ISSUE TITLE
Crafting Recipes for Vanilla Items create EMC exploits

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#623]
This is how this might be resolved kind of:

* Allow the mapper to overwrite values that were set, but this has the problem that some items will loose their characteristic EMC values (Iron will not stay at 256, because 256/9=28.44... , so nugget = 28 and 28x9 = 252 < 256) *config option?*
*  Log the EMC exploits the mapper encounters to a file, so the one doing the configuration can resolve this.

This is mostly a reminder to myself, i plan on implementing both these things.

**Comment by abraxas** [comment]
My suggestion is the latter.  I can imagine enough mods would lead to a feedback loop that either invalidated large swaths of EMC values (iron->nugget->something you can make with nuggets->iron (if you can melt that something back down), or only steps partway in (changes Iron, for example, but not things that can turn into iron)

I applaud a push to be exploit-free as long as we're otherwise vanilla, but not a lot of people use just one mod.

Also, many incoming EE2 fans enjoyed the opportunity to "try to figure it out" regarding exploitable EMC.

**Comment by MaPePeR** [comment]
The feedback-EMC loop already exists: craft nuggets into ingot. put ingot into condenser. get nuggets out. repeat.
At the moment the mapper is not allowed to overwrite values that were set to not ruin the values.

**Comment by williewillus** [comment]
i presume with the adding of the logging this is basically as fixed as it can get?
