### ISSUE TITLE
Unable to put items into Condenser via automation (

### ISSUE THREAD

**Issue by jamiemac262** [sinkillerj/ProjectE#624]
When i try and use pipes or AE to put items into the condenser it doesn't accept them.

**Comment by williewillus** [comment]
I can't reproduce with PE 1.4.3 and Buildcraft 6.4.8. Pipes insert items perfectly fine into condensers, both MKI and MKII

**Comment by Sourpowerpete** [comment]
He may be running into the same issue I ran into, which is you can't pump the same item that the condenser is making back into it. For example, I had uranium coming from a condenser and a ore processor, and I wanted both sources of uranium to be stored in the condenser until the big reactor needed it, but since the condenser was already producing uranium, it wouldn't accept any more from an outside source. It took me an hour to figure out what was going on.
