### ISSUE TITLE
"Returned null effectbounds for pedestal!" is spammed in console

### ISSUE THREAD

**Issue by Samario1** [sinkillerj/ProjectE#651]
Though only when they aren't loaded by a player
It seems to be a specific pedestal
A WoFT was in the pedestal, and it was on
it was speeding up a (finished) quarry

**Comment by sinkillerj** [comment]
Paging doctor @williewillus , looked into DMPedestalTile and the effectbounds are defined really oddly, any reason for this?

**Comment by williewillus** [comment]
All it does is check if the effect bounds is null, and if it is, create a new one centered on itself. Prevents a new AABB from being created each tick for no reason. What do you find odd about it?

I suspect this console spam is because of chunkloading weirdness or chunk thrashing, because TE objects get constructed and destructed when you load/unload chunks, and something is asking for the pedestal's effectbounds before it's reinitialized. Reporter said that it only happens when he's not near the pedestal, so that leads me to suspect it's related to chunkloading. Unfortunately, nothing we can do to work around vanilla to design. Currently things don't blow up because of null checks on everything but I can change it around to make more sense (perform null check before dynamic pedestal item dispatch) and remove the message.

**Comment by sinkillerj** [comment]
You shouldn't need to define the AABB in the update at all, you should be able to do it statically.

**Comment by williewillus** [comment]
....what? that makes no sense, each pedestal needs to have its own unique effectBounds. if it was static then they'd all affect the same region of space :p

**Comment by williewillus** [comment]
Oh unless you meant on object construction, I'll look at that right now.

**Comment by williewillus** [comment]
Update: TileEntity coordinates are set by MC's World and Chunk code after the constructor is called, we can't make effectBounds during construct-time because at that time it's not aware of its position or even its world yet (TE's are only constructed via an empty constructor overrided from ITileEntityProvider

**Comment by williewillus** [comment]
Either way things aren't blowing it, it's just log spam that can easily be redirected or removed, but I'm curious what's unloading and loading chunks so quickly

**Comment by Samario1** [comment]
Maybe it was the finished quarry next to it (quarries chunkload) fighting with spawn chunkloading?

**Comment by williewillus** [comment]
Perhaps, I'll need to test it more
