### ISSUE TITLE
Save bag and transmute data per player

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#652]
I have a really annoying issue on my server right now, where I feel some players data in project e has become corrupted, either due to a crash or something else, however, right now it stores it all in one file, making it impossible to delete that persons data without everyone else's. Is there anyway you can change the way it saves to do it per player instead.

**Comment by sinkillerj** [comment]
NBT files can be modified with: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by williewillus** [comment]
@sinkillerj in the long run, we really need to migrate to this. Having a single file creates a single point of failure if files ever get corrupted. I.E. if the crashes while player X's data is being written then all of players A-W's data get deleted as well. If it's separated then the other players' data is safe and we only lose one person's data.

I'm willing to figure it out if you're okay with it.

**Comment by Tencao** [comment]
Thats basically my problem right now, hence why I requested this.

**Comment by sinkillerj** [comment]
A single file is nothing new for mods, if you look in the world folder you will see that we are far from the only one using a single file, I believe even Thaumcraft does.

**Comment by Tencao** [comment]
I looked into the world folder under projectE, all I see is bagdata.dat, and knowledge.dat

**Comment by abaw7** [comment]
While a single file might make handling things easier, multiple files are better. Performance wise, you can dynamically load them in as you need them (So small, tiny hit when a player logs in), then you can unload them when they leave. This is a much better model to use while handling resources. On larger servers, loading in two very large files is resource intensive. On the server I'm currently running I have 312 users that i've logged in a little under two weeks. Of these, 11% are new, 88% are returning. It is simply a huge strain memory wise to load in a larger file while there is an alternative. Just because other mods do it does not mean it is the best way. There are always things that you can do to improve your code, this being one of them.

**Comment by abaw7** [comment]
Statistic wise, our bagdata and knowledge files are 518KB and 320KB respectively.

**Comment by sinkillerj** [comment]
@baw7 I agree that loading the whole file into RAM is a bad idea, and I'm not sure why we are, however the NBT format used by these files is MADE to be one file where anything in it can be accessed on demand, by splitting files NBT is pointless.

**Comment by Tencao** [comment]
If you dont want to move away from the whole one file system, can you at least make it so it only loads part of the file when needed, rather than the whole data. Also is there anyway you can either add a way to check for corrupted data and clear it on load, or add a way to manually clear a players data with an ingame command.

**Comment by sinkillerj** [comment]
@Tencao There is nothing for the bags right now, but there is: /projecte_clearKnowledge [username]

**Comment by williewillus** [comment]
I'm just more interested in splitting the file for safety reasons more than performance reasons. Having everything in one file makes me really uneasy about a server crash wiping everyone's data instead of just those who were online. And last time I checked thauncraft used individual player dats in the playerdata folder?

**Comment by Brycey92** [comment]
I also think having multiple knowledge and bag files would be a boost to performance on larger servers, and eliminate the single point of failure that currently exists with the single file. On my server of 600+ unique players, there is noticeable lag whenever ProjectE saves its alchemical bag and transmutation data.

One word of warning, though. We should switch the bags and knowledge to being associated to players' UUIDs instead of their usernames, as it currently is. This would prevent the need for a later conversion of hundreds of individual files to UUIDS, which would have considerable overhead.

**Comment by sinkillerj** [comment]
After the next build we will be updating the Forge version we compile against, in this version it should be safe to use UUID's. I was going to fix this awhile back until i learned why Moze used usernames.

**Comment by williewillus** [comment]
Of course, we could always use both systems together for a major version or two to make the transition easier instead of switching all at once.
And with UUID's you have the question of how to handle offline mode (if we're using external files, if we use player.dat it'll be fine)

**Comment by DZCreeper** [comment]
Config option for UUID vs name? Its fairly rare but offline mode servers would continue to work that way.

**Comment by MaPePeR** [comment]
so if we just use the player.dat everything would be fine and we would not even have to care about if we want to use UUID/Playername?

**Comment by Brycey92** [comment]
The only problem with that is that other mods and plugins can corrupt player.dat files on occasion, so a reset of the file would wipe the player's transmutation knowledge and alc bags too. That, and player.dat files use UUIDs anyway.

**Comment by abaw7** [comment]
Just wanted to make sure this didn't get forgotten.

**Comment by williewillus** [comment]
and it's a wrap! wooho \o/

**Comment by Brycey92** [comment]
Does that mean this has been implemented?

**Comment by MaPePeR** [comment]
yes

**Comment by williewillus** [comment]
@Brycey92 data is now saved inside the player.dat file, under the NBT Tags PEAlchBag and PETransmutation
