### ISSUE TITLE
EMC Issue with Custom Doors from Malisis Doors

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#661]
The mod Malisis Doors has a block I just found out about that allows you to generate custom doors.  Even better though, is that the doors themselves seem to carry EMC values.  However, some things do not appear to work correctly.

1) Although they have an EMC value, they cannot be put into the transmutation tablet.
2) The EMC value is incorrect.  It appears to be using the EMC value of whichever block was set into the top material slot.

**Comment by williewillus** [comment]
This is because the custom block Malisis Doors is using is doing some trickery to "steal" the tooltips of the ingredient blocks. Probably was a smart idea to copy lore tooltips from blocks, but in this case it just presents a fake EMC tooltip. The actual block has no value.

Fixing this would require lots of hacking around and odd detecting of whether our stack was actually a stack or not, etc. and isn't worth it for an edge-case aesthetic glitch. Sorry!

**Comment by sinkillerj** [comment]
Your best bet would be to contact the author of that mod, copying tooltips is something he probably shouldn't be doing for his purposes.
