### ISSUE TITLE
Transmutation Tablet search issues

### ISSUE THREAD

**Issue by xun468** [sinkillerj/ProjectE#678]
This is most frustrating with stone at the moment. When I search for stone in the tablet I get everything with the word stone in it's name but not the actual stone block. I know it's been learned but there's a lot of items in modpacks that have stone in the name. Also annoyingly enough chisel blocks have emc values and are considered their own entry, so I have about 5 different versions of sandstone cluttering up the table as well. If there's a way to get around this I apologize!

**Comment by partytown** [comment]
in the newest version there are tabs that you can scroll trough so even if there are 500 versions of stone ik thats not the case but then you can just scroll trough the pages and eventually you will find the stone that you are looking for. other than that idk of a way to do it otherwise other than just putting stone in the middle-right slot then that specific block will pop up at the top slot on the right side
