### ISSUE TITLE
Custom EMC with pregenerated values.

### ISSUE THREAD

**Issue by RoqueDeicide** [sinkillerj/ProjectE#699]
When modifying the custom EMC values, the file that contains the pregenerated values always takes precedence, which means that in order for the new custom EMC values to take effect the pregenerated_emc.json has to be deleted before running the command.

This isn't an issue really, it is actually useful since it allows registration of multiple EMC values at once without having to wait for the mapping to finish every time. It's just something not very obvious that I wanted to share.

Maybe the command should be added to invalidate the pregenerated_emc.json file and generate all of the values again? Like projecte_generateEMC.

projecte_reloadEMC command just loads the pregenerated values.

**Comment by MaPePeR** [comment]
its very intentional, that the pregenerated values overwrite the custom_emc file. 
I wanted the pregenerate file to be EXACTLY what you see in the game. 

Additional documentation how it is handled and how to use it is probably needed.

Because the file is not overwritten by anything you can also use it to view EMC changes: just generate 2 files and look at the changes in your favorite editor.

**Comment by RoqueDeicide** [comment]
> pregenerated values overwrite the custom_emc file

No, they don't. Pregenerated file basically contains the entire mapping data serialized in JSON and it does **include** data from custom_emc file. What I'm talking about is that the .json file is not immediately updated when custom_emc file is changed and you have to force the update by deleting it (the .json file).

**Comment by MaPePeR** [comment]
> Pregenerated file basically contains the entire mapping data serialized in JSON and it does include data from custom_emc file.
That is a better way to describe it.

The problem is, that the 'setValue' does not work on top of the pregenerated values, but the calculated values, that were written to the pregenerated files. So if the setValue command would automatically delete the pregenerated file it would destroy values you wrote into the file manually.

**Comment by RoqueDeicide** [comment]
> wrote into the file manually

Why would one write stuff into pregen file manually? I thought it was a file that contains serialized mapping data, so that data doesn't have to be generated every time the game is loaded.

I'm just suggesting adding a command that would regenerate the file, because doing so manually is needed to make changes to custom_emc file available in the game and it is a little finicky for server admins.

**Comment by MaPePeR** [comment]
The pregen file is also intended for emc mappings you cannot recalculate for some reasons. (At least i intended it for that - NEIMapper #691 could not work without pregenerated values)

But yea, i could understand a command for that.
