### ISSUE TITLE
Gem Helmet Night Vision Non-Functional

### ISSUE THREAD

**Issue by Maulkin12** [sinkillerj/ProjectE#735]
There seems to be a conflict between the Gem Helmet's nightvision effect and Ars Magica 2's Ender Affinity nightvision buff, and the former no longer works - and it prevents the latter from working while equipped. Moreover, the helmet's nightvision doesn't seem to work at all - I disabled all effects, drank some milk, got rid of ender affinity, restarted the game... and when I put the helmet back on, I got nothing.

It also seems that the helmet's effect can't be toggled, as the StepAssist can; perhaps this is a related issue?

Granted, this may just be some sort of config issue in my own version, as it used to work but now it doesn't, but I'm not sure how to check that. Any ideas?

**Comment by blackdragonIV** [comment]
@Maulkin12 

press shift + f to toggle the night vision on if still nothing, that is because you are in an area with high light level and the helmet auto disable night vision in strong lights , if still not working try to remove ars magica and test again , if still nothing then i cant help you further.

**Comment by Maulkin12** [comment]
Ah, excellent, thanks! I didn't know you pressed *shift* for nighteye, that seemed to work. Mind, it did uncover a new bug, and a potential workaround via tooltip...
