### ISSUE TITLE
Archangel Smite fix

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#749]
Archangel smite has been completely bugged for a while now, when will you fix it ? Was my favorite item ;C

**Comment by sinkillerj** [comment]
As of right now the Archangel's Smite is a WIP item, as such it is labelled with a WIP tag in game and has no recipe, until it has been completed no support is provided if you choose to use it.

**Comment by Carbon-Ghost** [comment]
What I wanted to know is when a fix is planned and if you need help for it ?

**Comment by williewillus** [comment]
PR's are always appreciated if you want to improve how they work. Currently my problem with the arrows is 1) They have weird facings when you initially fire them 2) It's not evident where they go - they jerk when they change direction and you're just left wondering where it went 3) When something gets killed all the other arrows that homed into the same mob just stutter around in the air, like it's trying to attack its spirit or something, instead of going for other mobs

**Comment by sinkillerj** [comment]
1. Could be solved by shooting straight till so many ticks have passed.
3. Should be a simple on update check fix.

**Comment by Carbon-Ghost** [comment]
Number 2 and 3 where also here in EE2, number 1 may be fixed easily if you set them facing a specific direction compared to you and set it to be static unless it begins to home ( then flight would also be static but you can fix this by setting a despawn time to the arrows ^.^ ), number 2 seems related to number 1, the spirit thing is because I think the game considers the mob to still be present for a few moments, so I don't see any fixes without counting Sin one :P
