### ISSUE TITLE
[dupe bug] Gem of eternal density

### ISSUE THREAD

**Issue by megamanzteam** [sinkillerj/ProjectE#761]
on player login in single player I had a gem set to dark matter in an alchemical chest. It is feed my smelted ores. I had a complete full chest of 64 dark matter. I have not tested on a server to determine if it happens there as well.

**Comment by MaPePeR** [comment]
The gem of eternal density does not check if the target item has an EMC value. (And due to threaded EMC Calculation nothing has a value in the first few ticks...) 

This needs to be fixed [here](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/GemEternalDensity.java#L108-L122).

**Comment by Tencao** [comment]
I can confirm this is a serious issue on servers too. a player showed me them duping tons of RM, by constantly changing the mod it converts stuff to, resulting in tons of RM

**Comment by MaPePeR** [comment]
@Tencao i think that this is a different and unrelated issue that has already been reported

**Comment by Tencao** [comment]
I'll make a new ticket about it, I just thought it would be related since it's to do with the EMC part of it.
