### ISSUE TITLE
ModelYue needs to be migrated to LayerRenderers

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#817]

**Comment by sinkillerj** [comment]
I see someone was impatient with me lol. Why did this need reflection though? Should be able to just call add layer through the event handler no?

**Comment by williewillus** [comment]
Just bored ;p
that event handler is fired every frame, so we can't know if we have added it yet without mucking about with static state or using reflection to query the map, both of which suck
Injecting it into the only two renderplayer instances at startup was a better option
The reflection is needed because skinMap is private and addLayer is protected

**Comment by sinkillerj** [comment]
Ah, was not aware of the addLayer protection, carry on citizen.
