### ISSUE TITLE
When exiting the end all known recipes get duped

### ISSUE THREAD

**Issue by MattsMc** [sinkillerj/ProjectE#836]
I have had multiple times now that i have been to the end and when i came back/went in (didn't look while i was in the end) it seemed to duplicate all the items i have learnt (it also dupes the dupes)

**Comment by williewillus** [comment]
This is because Mojang uses a extremely convoluted method to respawn players from the End -> Overworld >.<. Rather than something like what the nether portal and end entry portal use, the end exit portal basically kills the player and respawns them but keeps the data.
I had handling code that tracks when players are killed so they don't lose knowledge, and apparently the end exit triggers it as well.
Fix coming.
