### ISSUE TITLE
Pam's Desertcraft Exploit [1.7.10]

### ISSUE THREAD

**Issue by nephatrine** [sinkillerj/ProjectE#839]
This is may be an issue with how Pam coded her mod and not ProjectE, but there's a hilarious exploit with the cactus chestpiece from desertcraft. It is crafted with 8 cactus (should be ~64 EMC if I'm remembering value of cactus correctly). It's being valued at over 5000 EMC, however. I think this has to do with the fact that it comes with the Thorns enchantment on it and that is being figured into the value somehow. It's the only piece of the armor with the enchantment and the only one with this value issue. I've got a feedback loop setup right now taking advantage of this, but I feel a little bad doing so since it's such a big net gain.

If it's not something ProjectE can do anything about, maybe drop Pam a line and let her know if there's a better way to apply the enchantment that won't make the EMC value go crazy.

**Comment by sinkillerj** [comment]
Due to various factors such as machine output there are some things we cannot calculate and adjust for, however do keep in mind that at any time you can set a custom EMC value for a item making it much more sane.

I'll have to speak with @MaPePeR but you may be very well right about the enchantment being the cause, we may need to consider a config to disable enchantment bonuses if we do not have one already.

**Comment by MaPePeR** [comment]
We could check the NBT of the crafting output item for enchantments and subtract the enchantment bonus in the conversion.
That would cause the item to not have a value at all, though.
