### ISSUE TITLE
Fix/redo mercurial eye

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#845]
I don't know if anyone even uses it as it is, but the Mercurial Eye is broken (technical-wise) in 1.8, which I have yet to fix. 

I looked at it and in addition to being broken, it doesn't even seem feature-complete with what it was in EE2. I tried using it ingame in 1.7 and it was super clunky and frequently placed blocks onto my head as well. So I'm going to redo it soon, properly. Probably for 1.8 because of recent code cleanups that would make it much easier than doing it in 1.7 (blockpos stuff)

**Comment by HFSaphelion** [comment]
I have been trying to use it, but it will occasionally leave holes in the area I'm trying to fill. In my case specifically, I'm using it in SMP with a charged Klein Star Omega to fill in a huge @#$%ing hole that one of my server-mates dug into the world with a Destruction Catalyst. I'm trying to fill the hole in with regular stone blocks, but even fully powered up (where it should be making a 9x9 block square of stone), it will frequently leave empty holes in the wall which cannot be fixed with the mercurial eye. You HAVE to fill them by hand. I'm hoping this is the issue you are referring to and not another one. :/

**Comment by Heimdell** [comment]
I used this thing a lot. I insist on properly implementing the extension mode.

**Comment by Flexico** [comment]
I use this as well! I planned to build a castle with it, but without extension mode it's really clunky.

**Comment by pupnewfster** [comment]
Closed as this got fixed when #1824 was merged
