### ISSUE TITLE
Autopacker + Energy Condenser Mk 2 = crash

### ISSUE THREAD

**Issue by warriorsofcats** [sinkillerj/ProjectE#854]
I tried to use autopacker to pack the cobblestone that was generated in Energy Condenser Mk 2. That only lead to crash and give me this crash log - http://pastebin.com/Naw8dPUu

If I try to load the world again, it give me this different crash log - http://pastebin.com/EY6C013h

Only work around to get back into the world is to use McEdit to delete either a Energy condenser or a autopacker.

Let me know if you need more.

**Comment by sinkillerj** [comment]
You typically do not need to use MCEdit, and in fact thats actually pretty dangerous in some cases. Forge has a "removeErroring" option in its config made for situations like this.

That being said it appears this issue is the fault of the autopacker mod you are using, my best guess is that it tried to remove the lock target from the condenser.

**Comment by williewillus** [comment]
More precisely, it's this line causing it (passing a null itemstack to canExtract)
https://github.com/MCUpdater/AutoPackager/blob/master/src/main/java/org/mcupdater/autopackager/TilePackager.java#L87

I was about to see if it was our fault being unable to handle null there, but vanilla never calls it with null...so not our fault :D

**Comment by smbarbour** [comment]
No, it isn't trying to remove the locked item.  I would strongly recommend comparing the actual slot for extraction to the lock target instead of the the value passed in.  Do not rely on the behavior of the one thing in vanilla that uses this.
