### ISSUE TITLE
[1.9 BETA] Master Transmutation issue thread

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#944]
Please report all issues with the Transmutation interface in beta 1.9 here
Pinging @MaPePeR

**Comment by williewillus** [comment]
#1. http://pastebin.com/jnu4N2C3 by repeatedly spamming one item out on an MP server. Reported by Tencao

**Comment by williewillus** [comment]
as a side note, I don't think hacking around MC's dual-thread system is going to work well because of all the various different lag conditions that we can't possibly test. 

If there was a way for the searching to simply happen clientside, and all the client does is ask the server to put an item in your hand on click, that would be the best and simpler, with appropriate validation of course. Perhaps have the slots do nothing serverside and send a "please put X in my hand" packet clientside

**Comment by MaPePeR** [comment]
its not really hacking around in the dual thread system... And i really don't know what is causing that Exception...

I noticed, that we probably could reduce the size of the packets and the amount by using incremental packets and don't send packets when there is no real change.

> Edit: Though, allowing the client to specify X allows it to send arbitrary NBT to the server, which is very bad and why 1.8 had so many minors releases to cover it up

In 1.7.10 the client already does that, when you click a slot. The problem is, it does not do that, when you shift click a slot. That was my first attempt to read that packet and get the clicked slot content that way.

**Comment by williewillus** [comment]
Attempt to do it a different way: https://github.com/williewillus/ProjectE/commit/73e705316a08d29fa8d8271ed42e29d47a5f4c70

Didn't (or forgot to lol) reimplement emc cost nor shift clicking yet, but that is trivial if this can work

**Comment by williewillus** [comment]
This effort seems to be complete. Yay!
