### ISSUE TITLE
Items losing their EMC values

### ISSUE THREAD

**Issue by Apex-Blizzard** [sinkillerj/ProjectE#954]
I've added a lot of emc values to projecte. now all of a sudden, items are losing their values. is this a bug or is this intentional?

**Comment by MaPePeR** [comment]
Version of the mod? How did you add the emc values? Define 'losing their values'.

**Comment by blaisen** [comment]
I've had this issue as well, but not with items I've added myself. I've had oak logs just suddenly no longer have EMC values; chests as well; planks, sticks, modded items, you name it. Then if I restart my game, their values come back. It's frustrating; I have to get a chest, so I open my transmutation tablet, and it's forgotten chests. Then I look for planks to make the chest, they're not in there either. Then I look for logs to make planks -- whoops, no logs either. So I go chop down a tree, try to chuck the logs into the tablet, and it fails because they no longer have an EMC value. Then I have to restart minecraft, then chuck the logs in, then take the logs out, then make planks, chuck the planks in, take the planks out, make the chest, chuck the chest in, take a chest out. So much unnecessary work. Mod version: PE1.8.0 for Minecraft 1.7.10.

**Comment by MaPePeR** [comment]
@blaisen does that happen mid-game or only when you reenter a world?

**Comment by blaisen** [comment]
Yes.

**Comment by MaPePeR** [comment]
To what part of my 'or' question does your 'yes' belong to?

**Comment by blaisen** [comment]
To both. Random blocks and items will lose their EMC values and therefore be forgotten by the transmutation tablet both on login and randomly throughout gameplay.

**Comment by MaPePeR** [comment]
Does this happen in a specific modpack?

I cannot really reproduce this and i would imagine that if it would be very common our issue tracker would be full with reports like this...

**Comment by blaisen** [comment]
Custom modpack.

**Comment by MaPePeR** [comment]
Try to enable pregenerated emc in the mapping.cfg and see if the issue persists.
